import { afterEach, describe, it, expect, beforeEach, vi } from "vitest";
import { VideoOrchestrator } from "@/domain/services/VideoOrchestrator";
import { MockScriptWriter } from "@/mocks/MockScriptWriter";
import { MockVideoCompositor } from "@/mocks/MockVideoCompositor";
import { MockTTSService } from "@/mocks/MockTTSService";
import { MockStorageService } from "@/mocks/MockStorageService";
import { HeuristicDiffAnalyzer } from "@/infrastructure/diff/HeuristicDiffAnalyzer";
import type { IScriptWriter } from "@/interfaces/IScriptWriter";
import type { ITTSService } from "@/interfaces/ITTSService";
import type { CompositionInput, CompositionResult } from "@/interfaces/IVideoCompositor";
import type { PipelineCheckpoint } from "@/interfaces/IPipelineCheckpoint";
import type { VideoScript } from "@/domain/entities/VideoScript";
import { CONSTELLATION_SUFFIX_FRAMES } from "@/infrastructure/video/remotion/timing";
import { sanitizeSpokenNarrationText } from "@/lib/narrationText";
import {
  mockContext as baseMockContext,
  passthroughRetimeNarration,
} from "../../fixtures/orchestrator";

vi.mock("@/infrastructure/video/prepareClipAssets", () => ({
  prepareClipAssets: async (clips: Array<{
    sceneNumber: number;
    clipIndex: number;
    clipUrl: string;
    durationSeconds: number;
    durationFrames?: number;
  }>) =>
    clips.map((clip) => {
      const durationFrames = clip.durationFrames ?? Math.max(1, Math.round(clip.durationSeconds * 30));
      return { ...clip, durationFrames, durationSeconds: durationFrames / 30 };
    }),
}));

const mockContext = { ...baseMockContext };

describe("VideoOrchestrator", () => {
  let orchestrator: VideoOrchestrator;
  let storageService: MockStorageService;

  afterEach(() => {
    delete process.env.MODEL_PROMPT_ADAPTERS_V1;
    delete process.env.VIDEO_COMPOSITOR;
  });

  beforeEach(() => {
    storageService = new MockStorageService();
    orchestrator = new VideoOrchestrator({
      diffAnalyzer: new HeuristicDiffAnalyzer(),
      scriptWriter: new MockScriptWriter(),
      ttsService: new MockTTSService(),
      videoCompositor: new MockVideoCompositor(),
      storageService,
    });
  });

  it("executes the full pipeline and returns result", async () => {
    const result = await orchestrator.execute("test-job-id", mockContext);

    expect(result.objectKey).toContain("videos/owner/repo/42/test-job-id.mp4");
    expect(result.videoUrl).toContain("mock-r2.example.com");
    expect(result.script).toBeDefined();
    expect(result.script.scenes).toHaveLength(7);
    expect(result.script.changeType).toBe("feature");
  });

  it("uploads video to storage", async () => {
    const result = await orchestrator.execute("test-job-id", mockContext);
    expect(storageService.has(result.objectKey)).toBe(true);
  });

  it("does not inflate the opening code-first overview scene for constellation timing", async () => {
    process.env.VIDEO_COMPOSITOR = "remotion";

    let capturedInput: CompositionInput | undefined;
    const capturingCompositor = {
      compose: async (input: CompositionInput): Promise<CompositionResult> => {
        capturedInput = input;
        return { videoBuffer: Buffer.from("MOCK_VIDEO_DATA") };
      },
    };

    const orch = new VideoOrchestrator({
      diffAnalyzer: new HeuristicDiffAnalyzer(),
      scriptWriter: new MockScriptWriter(),
      ttsService: new MockTTSService(),
      videoCompositor: capturingCompositor,
      storageService: new MockStorageService(),
    });

    await orch.execute("code-first-constellation-opening-scene", {
      ...mockContext,
    });

    // Code-first clips are generated by generateClips(), not AI clip generator.
    // Scene 1 (overview, first scene) should NOT have constellation suffix.
    const scene1Clip = capturedInput?.clips[0];
    const scene2Clip = capturedInput?.clips[1];
    expect(scene1Clip).toBeDefined();
    expect(scene2Clip).toBeDefined();
    expect(scene1Clip!.sceneNumber).toBe(1);
    expect(scene2Clip!.sceneNumber).toBe(2);
    // Scene 1 (first scene) never gets constellation suffix.
    // Scene 2 (non-first, with codeBroll) gets constellation suffix.
    // In external TTS mode, clip durations are trimmed to actual narration length.
    // Scene 2's total = narrationFrames + CONSTELLATION_SUFFIX_FRAMES.
    // Verify the suffix is present by stripping it and checking the remainder is positive.
    const scene2Frames = scene2Clip?.durationFrames ?? 0;
    const scene2BaseFrames = scene2Frames - CONSTELLATION_SUFFIX_FRAMES;
    expect(scene2BaseFrames).toBeGreaterThan(0);
    // Scene 1 (first) must NOT include the suffix — its total equals narration only.
    // Scenes may have different narration lengths so a direct frame comparison is not
    // meaningful. We verify indirectly: scene 1's frames should be less than
    // scene2BaseFrames + 2 * CONSTELLATION_SUFFIX_FRAMES (i.e., scene1 was not
    // double-inflated), and scene 1's frames should be > 0.
    const scene1Frames = scene1Clip?.durationFrames ?? 0;
    expect(scene1Frames).toBeGreaterThan(0);
    // The key invariant: scene 2's total includes exactly one suffix, so its base
    // (total minus suffix) should be close to a reasonable narration length.
    expect(scene2BaseFrames).toBeGreaterThanOrEqual(1);
  });

  it("stores prompt pipeline V2 artifacts when the script writer returns them", async () => {
    const writerWithArtifacts: IScriptWriter = {
      generateScript: async (context, analysis) => {
        const base = await new MockScriptWriter().generateScript(context, analysis);
        return {
          ...base,
          promptPipelineV2: {
            enabled: true,
            llmFamily: "claude",
            coveragePlan: {
              summary: "Plan",
              selectedEvidencePolicy: "Cluster-selected evidence only.",
              clusters: [{
                clusterId: "c1",
                title: "Auth middleware",
                files: ["src/auth.ts"],
                evidenceSnippets: [{
                  filePath: "src/auth.ts",
                  summary: "Adds a guard",
                  diffExcerpt: "checkRateLimit();",
                }],
                technicalMechanism: "Block repeated requests before auth logic runs",
                impact: "Protects the endpoint from retries",
                riskIfAbsent: "Duplicate requests overwhelm the auth path",
                validationEvidence: ["auth tests"],
                importanceRank: 1,
              }],
              ledger: [{ clusterId: "c1", disposition: "deep_dive", reason: "Primary change" }],
              majorClusterIds: ["c1"],
            },
            sceneOutline: {
              scenes: [{
                sceneNumber: 1,
                sceneType: "overview",
                title: "Overview",
                clusterIds: ["c1"],
                evidenceFilePaths: ["src/auth.ts"],
                whatChanged: "Adds a guard",
                whyItMatters: "Protects the endpoint",
                failureWithoutIt: "Retries pile up",
                validation: "Auth tests cover the guard",
                visualFocus: "A doorman intercepting repeat visitors",
              }],
            },
          },
        };
      },
      retimeNarration: passthroughRetimeNarration,
    };
    const orch = new VideoOrchestrator({
      diffAnalyzer: new HeuristicDiffAnalyzer(),
      scriptWriter: writerWithArtifacts,
      ttsService: new MockTTSService(),
      videoCompositor: new MockVideoCompositor(),
      storageService,
    });

    await orch.execute("artifacts-job-id", mockContext);

    expect(storageService.has("scripts/owner/repo/42/artifacts-job-id/prompt-pipeline-v2.json")).toBe(true);
  });

  it("propagates script writer errors", async () => {
    const failingWriter = {
      generateScript: async () => {
        throw new Error("LLM API error");
      },
      retimeNarration: passthroughRetimeNarration,
    };

    const failOrchestrator = new VideoOrchestrator({
      diffAnalyzer: new HeuristicDiffAnalyzer(),
      scriptWriter: failingWriter,
      ttsService: new MockTTSService(),
      videoCompositor: new MockVideoCompositor(),
      storageService,
    });

    await expect(
      failOrchestrator.execute("test-job-id", mockContext),
    ).rejects.toThrow("LLM API error");
  });

  it("propagates TTS errors (external TTS path)", async () => {
    const failingTTS = {
      synthesize: async () => {
        throw new Error("TTS API error");
      },
    };

    const failOrchestrator = new VideoOrchestrator({
      diffAnalyzer: new HeuristicDiffAnalyzer(),
      scriptWriter: new MockScriptWriter(),
      ttsService: failingTTS,
      videoCompositor: new MockVideoCompositor(),
      storageService,
    });

    await expect(
      failOrchestrator.execute("test-job-id", mockContext),
    ).rejects.toThrow("TTS API error");
  });

  it("executeScriptOnly returns script and analysis without calling TTS/video/storage", async () => {
    const spyTTS = { synthesize: async () => { throw new Error("should not be called"); } };
    const spyCompositor = { compose: async () => { throw new Error("should not be called"); } };

    const scriptOnlyOrchestrator = new VideoOrchestrator({
      diffAnalyzer: new HeuristicDiffAnalyzer(),
      scriptWriter: new MockScriptWriter(),
      ttsService: spyTTS,
      videoCompositor: spyCompositor,
      storageService,
    });

    const result = await scriptOnlyOrchestrator.executeScriptOnly(
      "test-job-id",
      mockContext,
    );

    expect(result.script).toBeDefined();
    expect(result.script.scenes).toHaveLength(7);
    expect(result.analysis).toBeDefined();
    expect(result.analysis.totalFilesChanged).toBeGreaterThanOrEqual(0);
  });

  it("preserves scene durations in code-first mode (no model alignment)", async () => {
    const fixedDurationWriter: IScriptWriter = {
      generateScript: async (context) => {
        const base = await new MockScriptWriter().generateScript(
          context,
          {} as import("@/interfaces/IDiffAnalyzer").DiffAnalysis,
        );
        const scenes = base.script.scenes.map((scene) => ({
          ...scene,
          durationSeconds: 8,
        }));
        return {
          ...base,
          script: {
            ...base.script,
            scenes,
            totalDurationSeconds: scenes.length * 8,
          },
        };
      },
      retimeNarration: passthroughRetimeNarration,
    };

    const codeFirstOrchestrator = new VideoOrchestrator({
      diffAnalyzer: new HeuristicDiffAnalyzer(),
      scriptWriter: fixedDurationWriter,
      ttsService: new MockTTSService(),
      videoCompositor: new MockVideoCompositor(),
      storageService,
    });

    const result = await codeFirstOrchestrator.executeScriptOnly(
      "script-align-job",
      mockContext,
    );

    // Code-first mode: durations pass through unchanged (no model alignment)
    expect(result.script.scenes.every((scene) => scene.durationSeconds === 8)).toBe(true);
    expect(result.script.totalDurationSeconds).toBe(
      result.script.scenes.length * 8,
    );
  });

  it("executeScriptOnly propagates script writer errors", async () => {
    const failingWriter = {
      generateScript: async () => {
        throw new Error("LLM API error");
      },
      retimeNarration: passthroughRetimeNarration,
    };

    const failOrchestrator = new VideoOrchestrator({
      diffAnalyzer: new HeuristicDiffAnalyzer(),
      scriptWriter: failingWriter,
      ttsService: new MockTTSService(),
      videoCompositor: new MockVideoCompositor(),
      storageService,
    });

    await expect(
      failOrchestrator.executeScriptOnly("test-job-id", mockContext),
    ).rejects.toThrow("LLM API error");
  });

  // AI clip generator is not used in code-first mode — removed cinematic-only error propagation test.

  // AI clip prompt grounding is not applicable in code-first mode — clips are built from code, not AI prompts.

  // Closing directive for AI clip prompts is not applicable in code-first mode.

  it("propagates compositor errors", async () => {
    const failingCompositor = {
      compose: async () => {
        throw new Error("Composition failed");
      },
    };

    const failOrchestrator = new VideoOrchestrator({
      diffAnalyzer: new HeuristicDiffAnalyzer(),
      scriptWriter: new MockScriptWriter(),
      ttsService: new MockTTSService(),
      videoCompositor: failingCompositor,
      storageService,
    });

    await expect(
      failOrchestrator.execute("test-job-id", mockContext),
    ).rejects.toThrow("Composition failed");
  });

  describe("scene timing", () => {
    it("preserves scene durations from MockScriptWriter in code-first mode", async () => {
      const result = await orchestrator.execute("test-job-id", mockContext);

      // Code-first: scene durations come from the script writer and are not expanded by TTS measurement.
      // MockScriptWriter scene 4 has durationSeconds: 6 (architecture scene).
      expect(result.script.scenes[3].durationSeconds).toBe(6);
      expect(result.script.totalDurationSeconds).toBe(60);
    });

    it("passes the script timing to the compositor", async () => {
      let capturedInput: CompositionInput | undefined;
      const capturingCompositor = {
        compose: async (input: CompositionInput): Promise<CompositionResult> => {
          capturedInput = input;
          return { videoBuffer: Buffer.from("MOCK_VIDEO_DATA") };
        },
      };
      const orch = new VideoOrchestrator({
        diffAnalyzer: new HeuristicDiffAnalyzer(),
        scriptWriter: new MockScriptWriter(),
        ttsService: new MockTTSService(),
        videoCompositor: capturingCompositor,
        storageService: new MockStorageService(),
      });

      await orch.execute("test-job-id", mockContext);

      expect(capturedInput?.script.scenes[3].durationSeconds).toBe(6);
      expect(capturedInput?.script.totalDurationSeconds).toBe(60);
    });

    it("code-first clips use narration-derived durations (no model alignment)", async () => {
      let capturedInput: CompositionInput | undefined;
      const capturingCompositor = {
        compose: async (input: CompositionInput): Promise<CompositionResult> => {
          capturedInput = input;
          return { videoBuffer: Buffer.from("MOCK_VIDEO_DATA") };
        },
      };
      const ttsService = new MockTTSService();
      const scriptWriter: IScriptWriter = {
        generateScript: async () => ({
          script: {
            changeType: "feature",
            summary: "Long narration",
            headline: "",
            scenes: [
              {
                sceneNumber: 1,
                sceneType: "hook",
                durationSeconds: 4,
                narration: "The guard blocks duplicate requests before auth runs.",
                codeBroll: [],
              },
            ],
            totalDurationSeconds: 4,
            totalWordCount: 8,
            keyFiles: [],
            tags: [],
            narrativeRoles: [],
            voiceAssignments: [],
          },
        }),
        retimeNarration: async (
          _context,
          _analysis,
          script,
          _sceneBudgets,
          targetSceneNumbers,
        ) => ({
          scenes: script.scenes
            .filter((scene) => !targetSceneNumbers || targetSceneNumbers.includes(scene.sceneNumber))
            .map((scene) => ({
              sceneNumber: scene.sceneNumber,
              narration: "Guard blocks duplicates.",
            })),
        }),
      };
      const orch = new VideoOrchestrator({
        diffAnalyzer: new HeuristicDiffAnalyzer(),
        scriptWriter,
        ttsService,
        videoCompositor: capturingCompositor,
        storageService: new MockStorageService(),
      });

      await orch.execute("timing-test", mockContext);

      // Code-first: scene duration passes through unchanged (no model alignment)
      expect(capturedInput?.script.scenes[0].durationSeconds).toBe(4);
      expect(capturedInput?.script.totalDurationSeconds).toBe(4);
      // sceneTimelineFrames carries the code-first clip duration + per-scene audio
      expect(capturedInput?.sceneTimelineFrames).toEqual(
        expect.arrayContaining([
          expect.objectContaining({ sceneNumber: 1 }),
        ]),
      );
      expect(capturedInput?.sceneTimelineFrames[0].durationFrames).toBeGreaterThan(0);
    });

    it("stores per-scene word timings 0-based in sceneTimelineFrames for external TTS", async () => {
      let capturedInput: CompositionInput | undefined;
      const capturingCompositor = {
        compose: async (input: CompositionInput): Promise<CompositionResult> => {
          capturedInput = input;
          return { videoBuffer: Buffer.from("MOCK_VIDEO_DATA") };
        },
      };
      const scriptWriter: IScriptWriter = {
        generateScript: async () => ({
          script: {
            changeType: "feature",
            summary: "Scene holds",
            headline: "",
            scenes: [
              {
                sceneNumber: 1,
                sceneType: "hook",
                durationSeconds: 8,
                narration: "Guard holds.",
                codeBroll: [],
              },
              {
                sceneNumber: 2,
                sceneType: "summary",
                durationSeconds: 4,
                narration: "Second scene starts now.",
                codeBroll: [],
              },
            ],
            totalDurationSeconds: 12,
            totalWordCount: 6,
            keyFiles: [],
            tags: [],
            narrativeRoles: [],
            voiceAssignments: [],
          },
        }),
        retimeNarration: passthroughRetimeNarration,
      };
      const orch = new VideoOrchestrator({
        diffAnalyzer: new HeuristicDiffAnalyzer(),
        scriptWriter,
        ttsService: new MockTTSService(),
        videoCompositor: capturingCompositor,
        storageService: new MockStorageService(),
      });

      await orch.execute("scene-hold-test", mockContext);

      // Per-scene TTS: each scene's word timings are 0-based from that scene's audio start.
      // "Second" is the first word of scene 2, so its startTimeMs must be 0 (not offset to scene boundary).
      const scene2Timeline = capturedInput?.sceneTimelineFrames.find((e) => e.sceneNumber === 2);
      const secondWord = scene2Timeline?.wordTimings?.find((t) => t.word === "Second");
      expect(secondWord?.startTimeMs).toBe(0);
    });

    it("keeps the scripted scene duration when measured audio is shorter", async () => {
      let capturedInput: CompositionInput | undefined;
      const capturingCompositor = {
        compose: async (input: CompositionInput): Promise<CompositionResult> => {
          capturedInput = input;
          return { videoBuffer: Buffer.from("MOCK_VIDEO_DATA") };
        },
      };
      const scriptWriter: IScriptWriter = {
        generateScript: async () => ({
          script: {
            changeType: "feature",
            summary: "Ceiling duration test",
            headline: "",
            scenes: [
              {
                sceneNumber: 1,
                sceneType: "hook",
                durationSeconds: 4,
                narration: "Guard blocks duplicates.",
                codeBroll: [],
              },
            ],
            totalDurationSeconds: 4,
            totalWordCount: 3,
            keyFiles: [],
            tags: [],
            narrativeRoles: [],
            voiceAssignments: [],
          },
        }),
        retimeNarration: passthroughRetimeNarration,
      };
      const orch = new VideoOrchestrator({
        diffAnalyzer: new HeuristicDiffAnalyzer(),
        scriptWriter,
        ttsService: new MockTTSService(),
        videoCompositor: capturingCompositor,
        storageService: new MockStorageService(),
      });

      await orch.execute("ceiling-duration-test", mockContext);

      // Code-first: scene duration preserved from script (no model alignment)
      expect(capturedInput?.script.scenes[0].durationSeconds).toBe(4);
    });

    it("does not shrink a longer scene when measured audio is shorter than the script budget", async () => {
      let capturedInput: CompositionInput | undefined;
      const capturingCompositor = {
        compose: async (input: CompositionInput): Promise<CompositionResult> => {
          capturedInput = input;
          return { videoBuffer: Buffer.from("MOCK_VIDEO_DATA") };
        },
      };
      const scriptWriter: IScriptWriter = {
        generateScript: async () => ({
          script: {
            changeType: "feature",
            summary: "Short narration budget preservation",
            headline: "",
            scenes: [{
              sceneNumber: 1,
              sceneType: "hook",
              durationSeconds: 10,
              narration: "Tiny line.",
              codeBroll: [],
            }],
            totalDurationSeconds: 10,
            totalWordCount: 2,
            keyFiles: [],
            tags: [],
            narrativeRoles: [],
            voiceAssignments: [],
          },
        }),
        retimeNarration: passthroughRetimeNarration,
      };
      const orch = new VideoOrchestrator({
        diffAnalyzer: new HeuristicDiffAnalyzer(),
        scriptWriter,
        ttsService: new MockTTSService(),
        videoCompositor: capturingCompositor,
        storageService: new MockStorageService(),
      });

      await orch.execute("scene-budget-preservation-test", mockContext);

      // Code-first: scene duration preserved from script
      expect(capturedInput?.script.scenes[0].durationSeconds).toBe(10);
    });

    it("uses scene.durationSeconds directly for empty-narration scenes (no padding)", async () => {
      let capturedInput: CompositionInput | undefined;
      const capturingCompositor = {
        compose: async (input: CompositionInput): Promise<CompositionResult> => {
          capturedInput = input;
          return { videoBuffer: Buffer.from("MOCK_VIDEO_DATA") };
        },
      };
      const scriptWriter: IScriptWriter = {
        generateScript: async () => ({
          script: {
            changeType: "feature",
            summary: "Empty narration padding test",
            headline: "",
            scenes: [
              {
                sceneNumber: 1,
                sceneType: "hook",
                durationSeconds: 6,
                narration: "[SFX: keyboard clicks]",
                codeBroll: [],
              },
            ],
            totalDurationSeconds: 6,
            totalWordCount: 0,
            keyFiles: [],
            tags: [],
            narrativeRoles: [],
            voiceAssignments: [],
          },
        }),
        retimeNarration: passthroughRetimeNarration,
      };
      const orch = new VideoOrchestrator({
        diffAnalyzer: new HeuristicDiffAnalyzer(),
        scriptWriter,
        ttsService: new MockTTSService(),
        videoCompositor: capturingCompositor,
        storageService: new MockStorageService(),
      });

      await orch.execute("empty-narration-padding-test", mockContext);

      // Code-first: scene duration preserved from script (no model ceiling)
      expect(capturedInput?.script.scenes[0].durationSeconds).toBe(6);
    });

    it("falls back to word-timing estimate when audioDurationSeconds is 0", async () => {
      let capturedInput: CompositionInput | undefined;
      const capturingCompositor = {
        compose: async (input: CompositionInput): Promise<CompositionResult> => {
          capturedInput = input;
          return { videoBuffer: Buffer.from("MOCK_VIDEO_DATA") };
        },
      };
      const failedMeasurementTTS = {
        synthesize: async (text: string) => ({
          audioBuffer: Buffer.from("AUDIO"),
          wordTimings: text.split(/\s+/).filter(Boolean).map((w, i) => ({
            word: w,
            startTimeMs: i * 400,
            endTimeMs: (i + 1) * 400,
          })),
          audioDurationSeconds: 0,
        }),
      };
      const scriptWriter: IScriptWriter = {
        generateScript: async () => ({
          script: {
            changeType: "feature",
            summary: "Fallback test",
            headline: "",
            scenes: [{
              sceneNumber: 1,
              sceneType: "hook",
              durationSeconds: 5,
              narration: "Guard blocks duplicates.",
              codeBroll: [],
            }],
            totalDurationSeconds: 5,
            totalWordCount: 3,
            keyFiles: [],
            tags: [],
            narrativeRoles: [],
            voiceAssignments: [],
          },
        }),
        retimeNarration: passthroughRetimeNarration,
      };
      const orch = new VideoOrchestrator({
        diffAnalyzer: new HeuristicDiffAnalyzer(),
        scriptWriter,
        ttsService: failedMeasurementTTS,
        videoCompositor: capturingCompositor,
        storageService: new MockStorageService(),
      });

      await orch.execute("fallback-word-timing-test", mockContext);

      // Code-first: scene duration preserved from script
      expect(capturedInput?.script.scenes[0].durationSeconds).toBe(5);
    });

    it("falls back to scene.durationSeconds when both audioDurationSeconds and wordTimings are zero", async () => {
      // Both fallback tiers return zero — requestedSceneSeconds must use scene.durationSeconds
      // to avoid crashing computeClipCover with a zero target.
      let capturedInput: CompositionInput | undefined;
      const capturingCompositor = {
        compose: async (input: CompositionInput): Promise<CompositionResult> => {
          capturedInput = input;
          return { videoBuffer: Buffer.from("MOCK_VIDEO_DATA") };
        },
      };
      const doubleZeroTTS = {
        synthesize: async () => ({
          audioBuffer: Buffer.from("AUDIO"),
          wordTimings: [],
          audioDurationSeconds: 0,
        }),
      };
      const scriptWriter: IScriptWriter = {
        generateScript: async () => ({
          script: {
            changeType: "feature",
            summary: "Double-zero TTS fallback",
            headline: "",
            scenes: [{
              sceneNumber: 1,
              sceneType: "hook" as const,
              durationSeconds: 7,
              narration: "Short narration.",
              codeBroll: [],
            }],
            totalDurationSeconds: 7,
            totalWordCount: 2,
            keyFiles: [],
            tags: [],
            narrativeRoles: [],
            voiceAssignments: [],
          },
        }),
        retimeNarration: passthroughRetimeNarration,
      };
      const orch = new VideoOrchestrator({
        diffAnalyzer: new HeuristicDiffAnalyzer(),
        scriptWriter,
        ttsService: doubleZeroTTS,
        videoCompositor: capturingCompositor,
        storageService: new MockStorageService(),
      });

      // Must not throw (computeClipCover requires targetSeconds > 0)
      await orch.execute("double-zero-tts-fallback-test", mockContext);

      // Falls back to scene.durationSeconds = 7
      expect(capturedInput?.script.scenes[0].durationSeconds).toBe(7);
    });

    it("does not shrink a longer scene when measurement falls back to word timings", async () => {
      let capturedInput: CompositionInput | undefined;
      const capturingCompositor = {
        compose: async (input: CompositionInput): Promise<CompositionResult> => {
          capturedInput = input;
          return { videoBuffer: Buffer.from("MOCK_VIDEO_DATA") };
        },
      };
      const failedMeasurementTTS = {
        synthesize: async () => ({
          audioBuffer: Buffer.from("AUDIO"),
          wordTimings: [
            { word: "Tiny", startTimeMs: 0, endTimeMs: 400 },
            { word: "line.", startTimeMs: 400, endTimeMs: 800 },
            { word: "Again.", startTimeMs: 800, endTimeMs: 1200 },
          ],
          audioDurationSeconds: 0,
        }),
      };
      const scriptWriter: IScriptWriter = {
        generateScript: async () => ({
          script: {
            changeType: "feature",
            summary: "Fallback budget preservation",
            headline: "",
            scenes: [{
              sceneNumber: 1,
              sceneType: "hook",
              durationSeconds: 10,
              narration: "Tiny line. Again.",
              codeBroll: [],
            }],
            totalDurationSeconds: 10,
            totalWordCount: 3,
            keyFiles: [],
            tags: [],
            narrativeRoles: [],
            voiceAssignments: [],
          },
        }),
        retimeNarration: passthroughRetimeNarration,
      };
      const orch = new VideoOrchestrator({
        diffAnalyzer: new HeuristicDiffAnalyzer(),
        scriptWriter,
        ttsService: failedMeasurementTTS,
        videoCompositor: capturingCompositor,
        storageService: new MockStorageService(),
      });

      await orch.execute("fallback-scene-budget-test", mockContext);

      // Code-first: scene duration preserved from script
      expect(capturedInput?.script.scenes[0].durationSeconds).toBe(10);
    });

    it("passes productionAudio to TTS without including it in spoken text", async () => {
      let ttsInput = "";
      const recordingTTS = {
        synthesize: async (text: string) => {
          ttsInput = text;
          return { audioBuffer: Buffer.from("AUDIO"), wordTimings: [], audioDurationSeconds: 0 };
        },
      };
      const scriptWriter: IScriptWriter = {
        generateScript: async () => ({
          script: {
            changeType: "feature",
            summary: "Production audio separation",
            headline: "",
            scenes: [
              {
                sceneNumber: 1,
                sceneType: "hook",
                durationSeconds: 8,
                narration: "The auth guard blocks duplicate requests.",
                productionAudio: "heavy whoosh, low bass hit",
                codeBroll: [],
              },
              {
                sceneNumber: 2,
                sceneType: "summary",
                durationSeconds: 8,
                narration: "Retries stop at the entrance.",
                codeBroll: [],
              },
              {
                sceneNumber: 3,
                sceneType: "summary",
                durationSeconds: 8,
                narration: "Load stays under control.",
                codeBroll: [],
              },
              {
                sceneNumber: 4,
                sceneType: "closing",
                durationSeconds: 8,
                narration: "The endpoint stays responsive.",
                codeBroll: [],
              },
            ],
            totalDurationSeconds: 32,
            totalWordCount: 20,
            keyFiles: ["src/auth.ts"],
            tags: ["feature"],
            narrativeRoles: [],
            voiceAssignments: [],
          },
        }),
        retimeNarration: passthroughRetimeNarration,
      };
      const orch = new VideoOrchestrator({
        diffAnalyzer: new HeuristicDiffAnalyzer(),
        scriptWriter,
        ttsService: recordingTTS,
        videoCompositor: new MockVideoCompositor(),
        storageService: new MockStorageService(),
      });

      await orch.execute("test-production-audio", mockContext);

      // TTS should not receive productionAudio — it's non-spoken
      expect(ttsInput).not.toContain("heavy whoosh");
    });

    // Model prompt adapters are not used in code-first mode — AI clip generator is never called.
  });

  // applyThemePolicies tests removed — theme-specific speaking role caps no longer apply in code-first mode.

  describe("resume()", () => {
    it("reuses the checkpoint script unchanged when resuming from completedStep >= 5", async () => {
      const analysis = new HeuristicDiffAnalyzer().analyzeCorpus([]);
      const { script: baseScript } = await new MockScriptWriter().generateScript(mockContext, analysis);

      const checkpoints = new Map<string, PipelineCheckpoint>();
      const checkpointStore = {
        async save(c: PipelineCheckpoint) { checkpoints.set(c.jobId, c); },
        async load(jobId: string) { return checkpoints.get(jobId) ?? null; },
        async delete(jobId: string) { checkpoints.delete(jobId); },
      };
      checkpoints.set("resume-test", {
        jobId: "resume-test",
        completedStep: 5,
        prContext: mockContext,
        script: baseScript,
        audio: {
          audioUrl: "https://example.com/audio.ogg",
          audioKey: null,
          wordTimings: [{ word: "synthetic", startTimeMs: 0, endTimeMs: 100_000 }],
          audioIncluded: false,
        },
        clips: baseScript.scenes.map((s) => ({
          sceneNumber: s.sceneNumber,
          clipIndex: 0,
          clipUrl: `https://example.com/clip-${s.sceneNumber}.mp4`,
          durationSeconds: s.durationSeconds,
        })),
      });

      let capturedInput: CompositionInput | undefined;
      const capturingCompositor = {
        compose: async (input: CompositionInput): Promise<CompositionResult> => {
          capturedInput = input;
          return { videoBuffer: Buffer.from("MOCK_VIDEO_DATA") };
        },
      };

      const orch = new VideoOrchestrator({
        diffAnalyzer: new HeuristicDiffAnalyzer(),
        scriptWriter: new MockScriptWriter(),
        ttsService: new MockTTSService(),
        videoCompositor: capturingCompositor,
        storageService: new MockStorageService(),
        checkpointStore,
      });

      await orch.resume("resume-test");

      // Code-first: MockScriptWriter scene 4 (architecture) has durationSeconds: 6
      expect(capturedInput?.script.scenes[3].durationSeconds).toBe(baseScript.scenes[3].durationSeconds);
      expect(capturedInput?.script.totalDurationSeconds).toBe(baseScript.totalDurationSeconds);
    });

    it("preserves prompt pipeline V2 artifacts through checkpoint resume", async () => {
      const analysis = new HeuristicDiffAnalyzer().analyzeCorpus([]);
      const { script: baseScript } = await new MockScriptWriter().generateScript(mockContext, analysis);
      const promptPipelineV2 = {
        enabled: true as const,
        llmFamily: "claude" as const,
        coveragePlan: {
          summary: "Plan",
          selectedEvidencePolicy: "Cluster-selected evidence only.",
          clusters: [{
            clusterId: "c1",
            title: "Auth middleware",
            files: ["src/auth.ts"],
            evidenceSnippets: [{
              filePath: "src/auth.ts",
              summary: "Adds a guard",
              diffExcerpt: "checkRateLimit();",
            }],
            technicalMechanism: "Block repeated requests before auth logic runs",
            impact: "Protects the endpoint from retries",
            riskIfAbsent: "Duplicate requests overwhelm the auth path",
            validationEvidence: ["auth tests"],
            importanceRank: 1,
          }],
          ledger: [{ clusterId: "c1", disposition: "deep_dive" as const, reason: "Primary change" }],
          majorClusterIds: ["c1"],
        },
        sceneOutline: {
          scenes: [{
            sceneNumber: 1,
            sceneType: "overview" as const,
            title: "Overview",
            clusterIds: ["c1"],
            evidenceFilePaths: ["src/auth.ts"],
            whatChanged: "Adds a guard",
            whyItMatters: "Protects the endpoint",
            failureWithoutIt: "Retries pile up",
            validation: "Auth tests cover the guard",
            visualFocus: "A doorman intercepting repeat visitors",
          }],
        },
      };

      const checkpoints = new Map<string, PipelineCheckpoint>();
      const checkpointStore = {
        async save(c: PipelineCheckpoint) { checkpoints.set(c.jobId, c); },
        async load(jobId: string) { return checkpoints.get(jobId) ?? null; },
        async delete(jobId: string) { checkpoints.delete(jobId); },
      };
      checkpoints.set("resume-v2-artifacts", {
        jobId: "resume-v2-artifacts",
        completedStep: 5,
        prContext: mockContext,
        script: baseScript,
        promptPipelineV2,
        audio: {
          audioUrl: "https://example.com/audio.ogg",
          audioKey: null,
          wordTimings: [{ word: "synthetic", startTimeMs: 0, endTimeMs: 100_000 }],
          audioIncluded: false,
        },
        clips: baseScript.scenes.map((s) => ({
          sceneNumber: s.sceneNumber,
          clipIndex: 0,
          clipUrl: `https://example.com/clip-${s.sceneNumber}.mp4`,
          durationSeconds: s.durationSeconds,
        })),
      });

      const orch = new VideoOrchestrator({
        diffAnalyzer: new HeuristicDiffAnalyzer(),
        scriptWriter: new MockScriptWriter(),
        ttsService: new MockTTSService(),
        videoCompositor: new MockVideoCompositor(),
        storageService: new MockStorageService(),
        checkpointStore,
      });

      const result = await orch.resume("resume-v2-artifacts");

      expect(result.promptPipelineV2?.enabled).toBe(true);
      expect(result.promptPipelineV2?.coveragePlan.summary).toBe("Plan");
    });

    it("uses stored per-scene audio keys when resuming external TTS from completedStep === 4", async () => {
      const analysis = new HeuristicDiffAnalyzer().analyzeCorpus([]);
      const { script: baseScript } = await new MockScriptWriter().generateScript(mockContext, analysis);

      const checkpoints = new Map<string, PipelineCheckpoint>();
      const checkpointStore = {
        async save(c: PipelineCheckpoint) { checkpoints.set(c.jobId, c); },
        async load(jobId: string) { return checkpoints.get(jobId) ?? null; },
        async delete(jobId: string) { checkpoints.delete(jobId); },
      };

      const storageService = new MockStorageService();
      const storedPerSceneAudio = baseScript.scenes.slice(0, 2).map((s) => ({
        sceneNumber: s.sceneNumber,
        audioKey: `audio/owner/repo/42/resume-step4/scene-${s.sceneNumber}.ogg`,
        wordTimings: [{ word: "test", startTimeMs: 0, endTimeMs: 400 }],
        clipDurations: [5],
      }));
      // Pre-populate storage (simulates audio uploaded during original execution)
      for (const entry of storedPerSceneAudio) {
        await storageService.upload(entry.audioKey, Buffer.from("MOCK_AUDIO"), "audio/ogg");
      }

      checkpoints.set("resume-step4", {
        jobId: "resume-step4",
        completedStep: 4,
        prContext: mockContext,
        script: baseScript,
        perSceneAudio: storedPerSceneAudio,
      });

      let capturedInput: CompositionInput | undefined;
      const capturingCompositor = {
        compose: async (input: CompositionInput): Promise<CompositionResult> => {
          capturedInput = input;
          return { videoBuffer: Buffer.from("MOCK_VIDEO_DATA") };
        },
      };

      const orch = new VideoOrchestrator({
        diffAnalyzer: new HeuristicDiffAnalyzer(),
        scriptWriter: new MockScriptWriter(),
        ttsService: new MockTTSService(),
        videoCompositor: capturingCompositor,
        storageService,
        checkpointStore,
      });

      await orch.resume("resume-step4");

      // Should have re-signed per-scene audio URLs and merged into sceneTimelineFrames
      const scene1Timeline = capturedInput?.sceneTimelineFrames.find((e) => e.sceneNumber === 1);
      expect(scene1Timeline?.audioSrc).toBeDefined();
      expect(scene1Timeline?.wordTimings).toEqual([{ word: "test", startTimeMs: 0, endTimeMs: 400 }]);
    });

    it("re-synthesizes per-scene audio when resuming external TTS from completedStep < 4", async () => {
      const analysis = new HeuristicDiffAnalyzer().analyzeCorpus([]);
      const { script: baseScript } = await new MockScriptWriter().generateScript(mockContext, analysis);

      const checkpoints = new Map<string, PipelineCheckpoint>();
      const checkpointStore = {
        async save(c: PipelineCheckpoint) { checkpoints.set(c.jobId, c); },
        async load(jobId: string) { return checkpoints.get(jobId) ?? null; },
        async delete(jobId: string) { checkpoints.delete(jobId); },
      };
      checkpoints.set("resume-step2", {
        jobId: "resume-step2",
        completedStep: 2,
        prContext: mockContext,
        script: baseScript,
      });

      const ttsService = new MockTTSService();
      const ttsSpy = vi.spyOn(ttsService, "synthesize");

      let capturedInput: CompositionInput | undefined;
      const capturingCompositor = {
        compose: async (input: CompositionInput): Promise<CompositionResult> => {
          capturedInput = input;
          return { videoBuffer: Buffer.from("MOCK_VIDEO_DATA") };
        },
      };

      const orch = new VideoOrchestrator({
        diffAnalyzer: new HeuristicDiffAnalyzer(),
        scriptWriter: new MockScriptWriter(),
        ttsService,
        videoCompositor: capturingCompositor,
        storageService: new MockStorageService(),
        checkpointStore,
      });

      await orch.resume("resume-step2");

      // TTS should have been called for each scene with non-empty narration
      expect(ttsSpy).toHaveBeenCalled();
      // sceneTimelineFrames should include audio data
      const scene1 = capturedInput?.sceneTimelineFrames.find((e) => e.sceneNumber === 1);
      expect(scene1?.audioSrc).toBeDefined();
    });

    it("skips TTS and clip generation when resuming external TTS from completedStep === 5", async () => {
      const analysis = new HeuristicDiffAnalyzer().analyzeCorpus([]);
      const { script: baseScript } = await new MockScriptWriter().generateScript(mockContext, analysis);

      const storageService = new MockStorageService();
      const storedPerSceneAudio = baseScript.scenes.slice(0, 2).map((s) => ({
        sceneNumber: s.sceneNumber,
        audioKey: `audio/owner/repo/42/resume-step5/scene-${s.sceneNumber}.ogg`,
        wordTimings: [{ word: "hello", startTimeMs: 0, endTimeMs: 500 }],
        clipDurations: [5],
      }));
      for (const entry of storedPerSceneAudio) {
        await storageService.upload(entry.audioKey, Buffer.from("MOCK_AUDIO"), "audio/ogg");
      }

      const storedClips = baseScript.scenes.map((s) => ({
        sceneNumber: s.sceneNumber,
        clipIndex: 0,
        clipUrl: `https://example.com/clip-${s.sceneNumber}.mp4`,
        durationSeconds: s.durationSeconds,
        durationFrames: Math.round(s.durationSeconds * 30),
      }));

      const checkpoints = new Map<string, PipelineCheckpoint>();
      const checkpointStore = {
        async save(c: PipelineCheckpoint) { checkpoints.set(c.jobId, c); },
        async load(jobId: string) { return checkpoints.get(jobId) ?? null; },
        async delete(jobId: string) { checkpoints.delete(jobId); },
      };
      checkpoints.set("resume-step5", {
        jobId: "resume-step5",
        completedStep: 5,
        prContext: mockContext,
        script: baseScript,
        perSceneAudio: storedPerSceneAudio,
        clips: storedClips,
      });

      const ttsSpy = vi.fn();
      let capturedInput: CompositionInput | undefined;

      const orch = new VideoOrchestrator({
        diffAnalyzer: new HeuristicDiffAnalyzer(),
        scriptWriter: new MockScriptWriter(),
        ttsService: { synthesize: ttsSpy },
        videoCompositor: {
          compose: async (input: CompositionInput): Promise<CompositionResult> => {
            capturedInput = input;
            return { videoBuffer: Buffer.from("MOCK_VIDEO_DATA") };
          },
        },
        storageService,
        checkpointStore,
      });

      await orch.resume("resume-step5");

      // Should NOT re-synthesize
      expect(ttsSpy).not.toHaveBeenCalled();
      // sceneTimelineFrames should include re-signed audio URLs
      const scene1 = capturedInput?.sceneTimelineFrames.find((e) => e.sceneNumber === 1);
      expect(scene1?.audioSrc).toContain("mock-r2.example.com");
      expect(scene1?.wordTimings).toEqual([{ word: "hello", startTimeMs: 0, endTimeMs: 500 }]);
    });

    it("re-generates script when checkpoint has missing script", async () => {
      const staleAudioKeys = [
        "audio/owner/repo/42/legacy-resume/scene-1.ogg",
        "audio/owner/repo/42/legacy-resume/scene-2.ogg",
      ];
      const stalePerSceneAudio = staleAudioKeys.map((audioKey, i) => ({
        sceneNumber: i + 1,
        audioKey,
        wordTimings: [{ word: "stale", startTimeMs: 0, endTimeMs: 500 }],
        clipDurations: [5],
      }));

      const checkpoints = new Map<string, PipelineCheckpoint>();
      const checkpointStore = {
        async save(c: PipelineCheckpoint) { checkpoints.set(c.jobId, c); },
        async load(jobId: string) { return checkpoints.get(jobId) ?? null; },
        async delete(jobId: string) { checkpoints.delete(jobId); },
      };
      const legacyStorageService = new MockStorageService();
      for (const key of staleAudioKeys) {
        await legacyStorageService.upload(key, Buffer.from("STALE_AUDIO"), "audio/ogg");
      }

      checkpoints.set("legacy-resume", {
        jobId: "legacy-resume",
        completedStep: 5,
        prContext: mockContext,
        script: undefined as unknown as VideoScript,
        perSceneAudio: stalePerSceneAudio,
      });

      const scriptWriter = new MockScriptWriter();
      const generateSpy = vi.spyOn(scriptWriter, "generateScript");
      const deleteSpy = vi.spyOn(legacyStorageService, "delete");

      const orch = new VideoOrchestrator({
        diffAnalyzer: new HeuristicDiffAnalyzer(),
        scriptWriter,
        ttsService: new MockTTSService(),
        videoCompositor: new MockVideoCompositor(),
        storageService: legacyStorageService,
        checkpointStore,
      });

      const result = await orch.resume("legacy-resume");

      // Should have re-generated the script
      expect(generateSpy).toHaveBeenCalled();
      expect(result.script.summary).toBeDefined();

      // Code-first: clips are built by generateClips(), not the AI clip generator.
      // The pipeline still produces clips for the compositor.
      expect(result.script.scenes.length).toBeGreaterThan(0);

      // Stale audio keys from the pre-migration checkpoint must be cleaned up
      const deletedKeys = deleteSpy.mock.calls.map((c) => c[0]);
      for (const staleKey of staleAudioKeys) {
        expect(deletedKeys).toContain(staleKey);
      }
    });

    it("cleans up stale single-track audio.audioKey from legacy builtin-TTS checkpoint with missing script", async () => {
      const staleAudioKey = "audio/owner/repo/42/legacy-builtin/full-narration.ogg";

      const checkpoints = new Map<string, PipelineCheckpoint>();
      const checkpointStore = {
        async save(c: PipelineCheckpoint) { checkpoints.set(c.jobId, c); },
        async load(jobId: string) { return checkpoints.get(jobId) ?? null; },
        async delete(jobId: string) { checkpoints.delete(jobId); },
      };
      const legacyStorageService = new MockStorageService();
      await legacyStorageService.upload(staleAudioKey, Buffer.from("STALE"), "audio/ogg");

      checkpoints.set("legacy-builtin", {
        jobId: "legacy-builtin",
        completedStep: 4,
        prContext: mockContext,
        script: undefined as unknown as VideoScript,
        audio: { audioUrl: "", audioKey: staleAudioKey, wordTimings: [], audioIncluded: true },
      });

      const deleteSpy = vi.spyOn(legacyStorageService, "delete");

      const orch = new VideoOrchestrator({
        diffAnalyzer: new HeuristicDiffAnalyzer(),
        scriptWriter: new MockScriptWriter(),
        ttsService: new MockTTSService(),
        videoCompositor: new MockVideoCompositor(),
        storageService: legacyStorageService,
        checkpointStore,
      });

      await orch.resume("legacy-builtin");

      const deletedKeys = deleteSpy.mock.calls.map((c) => c[0]);
      expect(deletedKeys).toContain(staleAudioKey);
    });
  });

  describe("per-scene audio cleanup", () => {
    it("deletes per-scene audio files from storage after successful execution", async () => {
      const storageService = new MockStorageService();
      const orch = new VideoOrchestrator({
        diffAnalyzer: new HeuristicDiffAnalyzer(),
        scriptWriter: new MockScriptWriter(),
        ttsService: new MockTTSService(),
        videoCompositor: new MockVideoCompositor(),
        storageService,
      });

      await orch.execute("cleanup-test", mockContext);

      // Only the video key should remain — per-scene audio keys should be deleted
      const deleteSpy = vi.spyOn(storageService, "delete");
      // Re-run to capture the delete calls (first run already cleaned up)
      await orch.execute("cleanup-test-2", mockContext);

      const deleteKeys = deleteSpy.mock.calls.map((c) => c[0]);
      const audioDeleteKeys = deleteKeys.filter((k) => k.startsWith("audio/"));
      expect(audioDeleteKeys.length).toBeGreaterThan(0);
    });
  });

  describe("executeTTSOnly", () => {
    it("returns script + per-scene audio without generating clips or composing video", async () => {
      const spyCompositor = { compose: async () => { throw new Error("should not be called"); } };

      const ttsOnlyOrchestrator = new VideoOrchestrator({
        diffAnalyzer: new HeuristicDiffAnalyzer(),
        scriptWriter: new MockScriptWriter(),
        ttsService: new MockTTSService(),
        videoCompositor: spyCompositor,
        storageService,
      });

      const result = await ttsOnlyOrchestrator.executeTTSOnly("tts-only-job", mockContext);

      expect(result.script).toBeDefined();
      expect(result.script.scenes.length).toBeGreaterThan(0);
      expect(result.perSceneAudio).toBeDefined();
      expect(result.perSceneAudio.length).toBe(result.script.scenes.length);

      for (const audio of result.perSceneAudio) {
        expect(audio).toHaveProperty("sceneNumber");
        expect(audio).toHaveProperty("audioKey");
        expect(audio).toHaveProperty("wordTimings");
        expect(audio).toHaveProperty("clipDurations");
        expect(audio.clipDurations.length).toBeGreaterThan(0);
      }

      // At least some scenes should have audio URLs (non-empty narration)
      const withAudio = result.perSceneAudio.filter((a) => a.audioUrl);
      expect(withAudio.length).toBeGreaterThan(0);
    });

    it("calls synthesize() for each non-empty-narration scene without targetDurationSeconds in code-first mode", async () => {
      const spyTTS = new MockTTSService();
      const synthesizeSpy = vi.spyOn(spyTTS, "synthesize");

      const spyOrchestrator = new VideoOrchestrator({
        diffAnalyzer: new HeuristicDiffAnalyzer(),
        scriptWriter: new MockScriptWriter(),
        ttsService: spyTTS,
        videoCompositor: new MockVideoCompositor(),
        storageService,
      });

      const result = await spyOrchestrator.executeTTSOnly("tts-spy-job", mockContext);

      // Every non-empty-narration scene should trigger a TTS call
      for (const scene of result.script.scenes) {
        const sanitized = sanitizeSpokenNarrationText(scene.narration);
        if (!sanitized.trim()) continue;

        const matchingCall = synthesizeSpy.mock.calls.find(
          ([text]) => text === sanitized,
        );
        expect(matchingCall).toBeDefined();
        if (!matchingCall) throw new Error("unreachable");
        // Code-first: targetDurationSeconds is undefined (durations derived from word count)
        const options = matchingCall[2];
        expect(options?.targetDurationSeconds).toBeUndefined();
      }
    });

    it("propagates TTS errors", async () => {
      const failingTTS = {
        synthesize: async () => { throw new Error("TTS exploded"); },
      };

      const failOrchestrator = new VideoOrchestrator({
        diffAnalyzer: new HeuristicDiffAnalyzer(),
        scriptWriter: new MockScriptWriter(),
        ttsService: failingTTS,
        videoCompositor: new MockVideoCompositor(),
        storageService,
      });

      await expect(
        failOrchestrator.executeTTSOnly("tts-fail-job", mockContext),
      ).rejects.toThrow("TTS exploded");
    });

    it("clips use Math.ceil fallback (not DP-aligned durations) in code-first mode", async () => {
      // TTS returns 5.0s audio for a scene with durationSeconds=4.
      // With validDurations=[], computeClipCover falls back to Math.ceil(5.0)=[5],
      // NOT the DP-aligned [6] that validDurations=[4,6,8] would produce.
      const knownAudioSeconds = 5.0;
      const stubbedTTS: ITTSService = {
        synthesize: async () => ({
          audioBuffer: Buffer.from("stub"),
          wordTimings: [],
          audioDurationSeconds: knownAudioSeconds,
        }),
      };

      const singleSceneWriter: IScriptWriter = {
        generateScript: async () => ({
          script: {
            changeType: "feature",
            summary: "stub",
            headline: "",
            totalDurationSeconds: 4,
            totalWordCount: 4,
            keyFiles: [],
            tags: [],
            narrativeRoles: [],
            voiceAssignments: [],
            scenes: [{
              sceneNumber: 1,
              sceneType: "overview" as const,
              durationSeconds: 4, // shorter than audio — requestedSceneSeconds = narrationSeconds = 5.0
              narration: "one two three words",
              codeBroll: [],
            }],
          },
          promptPipelineV2: undefined,
        }),
        retimeNarration: passthroughRetimeNarration,
      };

      const orch = new VideoOrchestrator({
        diffAnalyzer: new HeuristicDiffAnalyzer(),
        scriptWriter: singleSceneWriter,
        ttsService: stubbedTTS,
        videoCompositor: new MockVideoCompositor(),
        storageService,
      });

      const result = await orch.executeTTSOnly("tts-ceil-job", mockContext);
      const scene1 = result.perSceneAudio.find((a) => a.sceneNumber === 1);
      expect(scene1?.clipDurations).toEqual([Math.ceil(knownAudioSeconds)]); // [5], not [6]
    });

    it("dead-air fix: clip uses actual narration duration when shorter than script durationSeconds", async () => {
      // Regression guard: old code used max(scriptDuration, narrationSeconds), producing dead air.
      // New code uses narrationSeconds directly — clip must be ~3s, not ~8s.
      const stubbedTTS: ITTSService = {
        synthesize: async () => ({
          audioBuffer: Buffer.from("stub"),
          wordTimings: [],
          audioDurationSeconds: 3.0,
        }),
      };

      const writer: IScriptWriter = {
        generateScript: async () => ({
          script: {
            changeType: "feature",
            summary: "stub",
            headline: "",
            totalDurationSeconds: 8,
            totalWordCount: 4,
            keyFiles: [],
            tags: [],
            narrativeRoles: [],
            voiceAssignments: [],
            scenes: [{
              sceneNumber: 1,
              sceneType: "overview" as const,
              durationSeconds: 8, // much longer than TTS output
              narration: "one two three words",
              codeBroll: [],
            }],
          },
          promptPipelineV2: undefined,
        }),
        retimeNarration: passthroughRetimeNarration,
      };

      const orch = new VideoOrchestrator({
        diffAnalyzer: new HeuristicDiffAnalyzer(),
        scriptWriter: writer,
        ttsService: stubbedTTS,
        videoCompositor: new MockVideoCompositor(),
        storageService,
      });

      const result = await orch.executeTTSOnly("dead-air-regression", mockContext);
      const scene1 = result.perSceneAudio.find((a) => a.sceneNumber === 1);
      // Clip must cover ~3s (the actual TTS duration), not ~8s (the LLM's script estimate).
      const totalClipSeconds = (scene1?.clipDurations ?? []).reduce((a, b) => a + b, 0);
      expect(totalClipSeconds).toBeLessThanOrEqual(4); // 3s narration → ceil(3)=3, not 8
      expect(totalClipSeconds).toBeGreaterThan(0);
    });

    it("execute() returns actualDurationMs summed from rendered timeline (not script estimate)", async () => {
      // Billing parity: when narration runs faster than scripted durationSeconds,
      // the rendered video is shorter than script.totalDurationSeconds. Billing
      // must use the actual rendered duration, not the script estimate.
      const stubbedTTS: ITTSService = {
        synthesize: async () => ({
          audioBuffer: Buffer.from("stub"),
          wordTimings: [{ word: "stub", startTimeMs: 0, endTimeMs: 3000 }],
          audioDurationSeconds: 3.0,
        }),
      };

      const writer: IScriptWriter = {
        generateScript: async () => ({
          script: {
            changeType: "feature",
            summary: "stub",
            headline: "",
            totalDurationSeconds: 8,
            totalWordCount: 1,
            keyFiles: [],
            tags: [],
            narrativeRoles: [],
            voiceAssignments: [],
            scenes: [{
              sceneNumber: 1,
              sceneType: "overview" as const,
              durationSeconds: 8,
              narration: "stub",
              codeBroll: [],
            }],
          },
          promptPipelineV2: undefined,
        }),
        retimeNarration: passthroughRetimeNarration,
      };

      const orch = new VideoOrchestrator({
        diffAnalyzer: new HeuristicDiffAnalyzer(),
        scriptWriter: writer,
        ttsService: stubbedTTS,
        videoCompositor: new MockVideoCompositor(),
        storageService,
      });

      const result = await orch.execute("billing-parity-job", mockContext);
      const actualDurationMs = result.actualDurationMs;
      if (actualDurationMs === undefined) {
        throw new Error("execute() must populate actualDurationMs from sceneTimelineFrames");
      }
      expect(result.sceneTimelineFrames).toBeDefined();
      const totalFrames = (result.sceneTimelineFrames ?? []).reduce((sum, e) => sum + e.durationFrames, 0);
      const expectedDurationMs = Math.round((totalFrames / 30) * 1000);
      expect(actualDurationMs).toBe(expectedDurationMs);
      // Rendered video is closer to narration (~3s) than to script estimate (~8s).
      expect(actualDurationMs).toBeLessThan(8000);
    });
  });

  describe("deleteCheckpoint resilience", () => {
    it("returns pipeline result even when checkpointStore.delete() throws", async () => {
      const throwingCheckpointStore: import("@/interfaces/IPipelineCheckpoint").IPipelineCheckpointStore = {
        save: async () => {},
        load: async () => null,
        delete: async () => { throw new Error("Storage unavailable"); },
      };

      const orchWithCheckpoint = new VideoOrchestrator({
        diffAnalyzer: new HeuristicDiffAnalyzer(),
        scriptWriter: new MockScriptWriter(),
        ttsService: new MockTTSService(),
        videoCompositor: new MockVideoCompositor(),
        storageService,
        checkpointStore: throwingCheckpointStore,
      });

      const result = await orchWithCheckpoint.execute("checkpoint-fail-job", mockContext);

      expect(result.objectKey).toContain("videos/owner/repo/42/checkpoint-fail-job.mp4");
      expect(result.videoUrl).toBeDefined();
      expect(result.script.scenes.length).toBeGreaterThan(0);
    });
  });

  describe("script artifact storage", () => {
    it("uploads script.json and narration.txt after successful execution", async () => {
      await orchestrator.execute("test-job-id", mockContext);

      expect(storageService.has("scripts/owner/repo/42/test-job-id/script.json")).toBe(true);
      expect(storageService.has("scripts/owner/repo/42/test-job-id/narration.txt")).toBe(true);
    });

    it("script.json contains valid JSON matching the generated script", async () => {
      await orchestrator.execute("test-job-id", mockContext);

      const buffer = storageService.get("scripts/owner/repo/42/test-job-id/script.json");
      expect(buffer).toBeDefined();
      if (!buffer) throw new Error("unreachable");

      const parsed = JSON.parse(buffer.toString("utf-8")) as Record<string, unknown>;
      expect(Array.isArray(parsed.scenes)).toBe(true);
      expect((parsed.scenes as unknown[]).length).toBeGreaterThan(0);
      expect(typeof parsed.totalDurationSeconds).toBe("number");
    });

    it("narration.txt contains scene markers and narration text", async () => {
      await orchestrator.execute("test-job-id", mockContext);

      const buffer = storageService.get("scripts/owner/repo/42/test-job-id/narration.txt");
      expect(buffer).toBeDefined();
      if (!buffer) throw new Error("unreachable");

      const text = buffer.toString("utf-8");
      expect(text).toContain("--- Scene 1");
      expect(text).toContain("(overview)");
      // First scene narration from code-first MockScriptWriter
      expect(text).toContain("walkthrough mode");
    });
  });

  // visualPromptJudge tests removed — the judge was a no-op (always skipped
  // in code-first mode) and has been removed from the codebase.

});
