import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { verifyToken } from "@/lib/shareToken";
import { getContainer } from "@/config/container";
import { createLogger } from "@/lib/logger";

const logger = createLogger("watch/page");

interface WatchPageProps {
  params: Promise<{ jobId: string }>;
  searchParams: Promise<{ token?: string }>;
}

export async function generateMetadata({
  params,
  searchParams,
}: WatchPageProps): Promise<Metadata> {
  const { jobId } = await params;
  const { token } = await searchParams;
  const secret = process.env.SHARE_SIGNING_SECRET;

  if (!token || !secret) {
    return { title: "PrVod", robots: "noindex" };
  }

  const payload = verifyToken(token, secret);
  if (!payload || payload.jobId !== jobId || payload.type !== "video") {
    return { title: "Link Expired · PrVod", robots: "noindex" };
  }

  try {
    const container = await getContainer();
    const job = await container.jobRepository.findById(jobId);
    if (!job?.videoUrl) {
      return { title: "PrVod", robots: "noindex" };
    }
    const metrics = job.metricsJson as Record<string, unknown> | null;
    const prTitle =
      (metrics?.prTitle as string) ?? `#${job.prNumber}`;

    return {
      title: `PR Walkthrough · ${job.repoFullName} ${prTitle} · PrVod`,
      description: `Code review walkthrough for ${prTitle}`,
      robots: "noindex",
    };
  } catch {
    return { title: "PrVod", robots: "noindex" };
  }
}

export default async function WatchPage({ params, searchParams }: WatchPageProps) {
  const { jobId } = await params;
  const { token } = await searchParams;

  const secret = process.env.SHARE_SIGNING_SECRET;
  if (!token) {
    redirect("https://prvod.dev");
  }

  if (!secret) {
    logger.error("SHARE_SIGNING_SECRET not configured");
    return <ExpiredPage />;
  }

  const payload = verifyToken(token, secret);
  if (!payload || payload.jobId !== jobId || payload.type !== "video") {
    logger.debug("Watch page: invalid or expired token", { jobId });
    return <ExpiredPage />;
  }

  let videoUrl: string | null = null;
  let repoFullName = "";
  let prNumber = 0;
  let prTitle = "";

  try {
    const container = await getContainer();
    const job = await container.jobRepository.findById(jobId);

    if (!job?.videoUrl) {
      logger.debug("Watch page: job not found or no video", { jobId });
      return <ExpiredPage message="This walkthrough is no longer available." />;
    }

    videoUrl = job.videoUrl;
    repoFullName = job.repoFullName;
    prNumber = job.prNumber;
    const metrics = job.metricsJson as Record<string, unknown> | null;
    prTitle = (metrics?.prTitle as string) ?? `#${prNumber}`;
  } catch (err) {
    logger.error("Watch page: failed to load job", {
      jobId,
      error: err instanceof Error ? err.message : String(err),
    });
    return <ExpiredPage message="Unable to load this walkthrough right now." />;
  }

  return (
    <div className="flex min-h-screen flex-col bg-[var(--background)]">
      {/* Header */}
      <header className="flex items-center justify-between border-b border-[var(--border)] px-6 py-4">
        <a
          href="https://prvod.dev"
          className="font-[family-name:var(--font-display)] text-lg font-bold tracking-tight text-[var(--foreground)]"
        >
          PrVod
        </a>
        <div className="text-sm text-[var(--foreground-muted)]">
          <span className="font-mono text-[var(--foreground-soft)]">{repoFullName}</span>
          {" "}
          <span className="text-[var(--foreground)]">{prTitle}</span>
        </div>
      </header>

      {/* Video */}
      <main className="flex flex-1 items-center justify-center p-4 md:p-8">
        <div className="w-full max-w-4xl">
          <video
            controls
            autoPlay={false}
            className="w-full rounded-xl border border-[var(--border)] shadow-[var(--shadow-cinematic)]"
            src={videoUrl}
          >
            Your browser does not support the video element.
          </video>
        </div>
      </main>

      {/* Footer CTA */}
      <footer className="border-t border-[var(--border)] px-6 py-4 text-center">
        <p className="text-sm text-[var(--foreground-soft)]">
          Generated by{" "}
          <a
            href="https://prvod.dev"
            className="font-medium text-[var(--accent)] hover:underline"
          >
            PrVod
          </a>
          {" · "}Code review walkthroughs, automatically.
        </p>
        <a
          href="https://prvod.dev"
          className="mt-2 inline-block text-sm font-medium text-[var(--accent)] hover:underline"
        >
          Get PrVod for your team →
        </a>
      </footer>
    </div>
  );
}

function ExpiredPage({ message }: { message?: string }) {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-[var(--background)] px-6">
      <a
        href="https://prvod.dev"
        className="mb-8 font-[family-name:var(--font-display)] text-2xl font-bold tracking-tight text-[var(--foreground)]"
      >
        PrVod
      </a>
      <div className="rounded-xl border border-[var(--border)] bg-[var(--background-panel)] p-8 text-center shadow-lg">
        <h1 className="mb-2 text-xl font-semibold text-[var(--foreground)]">
          {message ?? "This link has expired"}
        </h1>
        <p className="mb-6 text-sm text-[var(--foreground-muted)]">
          Ask the owner to share a new link.
        </p>
        <a
          href="https://prvod.dev"
          className="text-sm font-medium text-[var(--accent)] hover:underline"
        >
          Learn about PrVod →
        </a>
      </div>
    </div>
  );
}
