import type { LegitimateFixture } from "./types";

/**
 * Category 3: Base64/encoding PRs
 *
 * Config files with base64 values, JWT tokens in test fixtures, encoded
 * image data, and certificate blobs.  These trigger ee-base64-block (>50
 * char base64 runs) in non-permissive fields but are completely benign.
 */
export const base64EncodingFixtures: LegitimateFixture[] = [
  {
    name: "jwt-test-fixtures-with-long-tokens",
    category: "base64-encoding",
    prTitle: "chore: add JWT signing config and TLS cert fixtures",
    prDescription:
      "Adds configuration for JWT signing with RS256 and includes base64-encoded test certificates " +
      "for mTLS in the staging environment.",
    diff: [
      "diff --git a/config/auth.ts b/config/auth.ts",
      "index 4d5e6f7..8a9b0c1 100644",
      "--- a/config/auth.ts",
      "+++ b/config/auth.ts",
      "@@ -1,4 +1,9 @@",
      " export const authConfig = {",
      "   algorithm: 'RS256',",
      "   issuer: 'https://auth.example.com',",
      "+  // Test-only public key (not a secret)",
      "+  testPublicKey: 'LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE3d0d6',",
      "+  // Example JWT for integration tests (expired, test-only)",
      "+  testJwt: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IlRlc3QgVXNlciIsImlhdCI6MTUxNjIzOTAyMn0.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c',",
      "+  tokenPrefix: 'Bearer',",
      " };",
    ].join("\n"),
    issues: ["Set up mTLS for staging environment"],
    milestone: "v1.3 - Infrastructure",
    expectedTriggerPatterns: ["ee-base64-block"],
  },
  {
    name: "base64-encoded-image-assets",
    category: "base64-encoding",
    prTitle: "feat: add inline SVG and PNG fallback as base64 data URIs",
    prDescription:
      "Embeds small icon assets as base64 data URIs to avoid extra HTTP requests. " +
      "The encoded strings are long but are legitimate image data, not obfuscated payloads.",
    diff: [
      "diff --git a/src/assets/icons.ts b/src/assets/icons.ts",
      "index 0000000..a3b4c5d 100644",
      "--- /dev/null",
      "+++ b/src/assets/icons.ts",
      "@@ -0,0 +1,18 @@",
      "+/** Inline base64-encoded 16x16 PNG icons to avoid network requests. */",
      "+export const ICONS = {",
      "+  check: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAAdgAAAHYBTnsmCAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAADlSURBVDiN',",
      "+  error: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAABlBMVEUAAAD/AABSFQmFAAAAAXRSTlMAQObYZgAAADlJREFUGNNjYIAARjANA2xskDQDI5gNFmBgBNEwNhOYBpFMYD',",
      "+  warning: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCI+PHBhdGggZD0iTTEyIDJMMyAyMGgyMnoiIGZpbGw9Im9yYW5nZSIvPjwvc3ZnPg==',",
      "+} as const;",
    ].join("\n"),
    issues: [],
    milestone: "",
    expectedTriggerPatterns: ["ee-base64-block"],
  },
  {
    name: "protobuf-serialized-fixtures",
    category: "base64-encoding",
    prTitle: "test: add base64-encoded protobuf test fixtures",
    prDescription:
      "Adds pre-serialized protobuf messages as base64 for snapshot testing. " +
      "These are deterministic golden files generated by the proto compiler.",
    diff: [
      "diff --git a/tests/fixtures/proto-snapshots.ts b/tests/fixtures/proto-snapshots.ts",
      "index 0000000..d6e7f8a 100644",
      "--- /dev/null",
      "+++ b/tests/fixtures/proto-snapshots.ts",
      "@@ -0,0 +1,22 @@",
      "+/**",
      "+ * Golden protobuf fixtures -- base64-encoded binary messages.",
      "+ * Regenerate with: npm run proto:generate-fixtures",
      "+ */",
      "+export const PROTO_FIXTURES = {",
      "+  userCreated: {",
      "+    description: 'UserCreated event with all fields populated',",
      "+    base64: 'CgpKb2huIFNtaXRoEhRqb2huQGV4YW1wbGUuY29tGgVhZG1pbiIkYjdlNjFmM2EtM2Q0Ny00NjBlLWE1ZTctY2UyZTNlZjBkYmVmKgkI2/yJswYQADIJCL2AirMGEAA=',",
      "+  },",
      "+  orderPlaced: {",
      "+    description: 'OrderPlaced event with 3 line items',",
      "+    base64: 'CAESJGMzMWE1ZmQyLTg5NGItNDJmYi1hYzUyLTk3NjFjODc5M2RlNRoUChBXaWRnZXQgUHJvIE1heCAxEAEaFAoQV2lkZ2V0IFBybyBNYXggMhACGhQKEFdpZGdldCBQcm8gTWF4IDMQAyIJCNaei7MGEAA=',",
      "+  },",
      "+  emptyPayload: {",
      "+    description: 'Minimal message with only required fields',",
      "+    base64: 'CAES',",
      "+  },",
      "+} as const;",
    ].join("\n"),
    issues: ["Add deterministic protobuf snapshot tests"],
    milestone: "v1.4 - Testing",
    expectedTriggerPatterns: ["ee-base64-block"],
  },
];
