/**
 * Error-comment builders for the GitHub webhook route.
 *
 * Extracted from `route.ts` because Next.js does not allow arbitrary named
 * exports on route files (only the HTTP verb handlers). Placing the helper
 * here keeps it trivially testable without test-only export hacks.
 *
 * LOOP-GUARD: The copyable `@prvod` mention is inline prose (e.g.
 * "by commenting `@prvod`"). The annotation parser (`ANNOTATION_LINE_PATTERN`)
 * is line-anchored (`^...$` with `m` flag) so it cannot match inline occurrences.
 * Primary defense is `isBotAuthoredIssueComment` in the webhook route.
 */

/** Pre-compiled patterns for rate-limit detection (avoids per-call regex allocation). */
const RATE_LIMIT_PATTERNS: RegExp[] = [
  /\b429\b/,
  /too many requests/i,
  /rate[- ]?limit/i,
  /resource[_ ]exhausted/i,
  /no capacity available/i,
  /model[_ ]capacity[_ ]exhausted/i,
  /overloaded/i,
];

/**
 * Detects an LLM rate-limit exhaustion failure so we can surface a specific
 * message rather than the generic "try again" copy.
 */
export function isRateLimitErrorMessage(errorMessage: string): boolean {
  return (
    errorMessage.includes("LLM_RATE_LIMITED_EXHAUSTED") ||
    RATE_LIMIT_PATTERNS.some((re) => re.test(errorMessage))
  );
}

export function buildErrorComment(errorMessage: string): string {
  const HEADER = "### 🎬 PrVod";
  const FOOTER = "---\n*Generated by [PrVod](https://prvod.dev)*";

  // Literal `@prvod` is safe inline: the annotation parser is line-anchored
  // and cannot match inside prose like "by commenting `@prvod`".
  const body = isRateLimitErrorMessage(errorMessage)
    ? [
        "⏳ Video generation failed because the underlying LLM provider is rate-limited or over capacity.",
        "The pipeline retried the LLM call with exponential backoff and the provider is still refusing the request.",
        "",
        "Try again in a few minutes by commenting `@prvod` on this PR. If the issue persists, switching to a different model (e.g. `gemini-2.5-flash` or a Claude model) may help.",
      ].join("\n")
    : "😞 Video generation failed. Please try again by commenting `@prvod` on this PR.";

  return `${HEADER}\n\n${body}\n\n${FOOTER}`;
}
