import { NextResponse } from "next/server";
import { getContainer } from "@/config/container";
import { PipelineRunner } from "@/domain/services/PipelineRunner";
import { verifyGitHubSignature, parseAnnotations } from "@/lib/webhookSignature";
import { createLogger } from "@/lib/logger";
import { webhookRateLimiter } from "@/app/api/webhook/github/rateLimiter";
import type { PRContext } from "@/domain/entities/PRContext";
import type { IJobRepository } from "@/interfaces/IJobRepository";
import type { VideoJob } from "@/domain/entities/VideoJob";
import type { InstallationRecord } from "@/interfaces/IInstallationRepository";
import type { IPipelineCheckpointStore } from "@/interfaces/IPipelineCheckpoint";
import { buildErrorComment } from "@/app/api/webhook/github/errorComment";
import { createPipelineRunner } from "@/app/api/pipelineFactory";

const logger = createLogger("webhook/github");

// Validates repoFullName matches the owner/repo format before URL construction
const REPO_FULL_NAME_REGEX = /^[a-zA-Z0-9._-]+\/[a-zA-Z0-9._-]+$/;
const RECEIVED_RETRY_AFTER_MS = 5 * 60 * 1000;

// ── Helpers ──────────────────────────────────────────────────────────────────

function buildReviewPageUrl(jobId: string): string {
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "https://localhost:3000";
  const base = appUrl.endsWith("/") ? appUrl.slice(0, -1) : appUrl;
  const url = `${base}/reviews/${encodeURIComponent(jobId)}`;
  // Basic validation — catch misconfigured NEXT_PUBLIC_APP_URL early
  try {
    new URL(url);
  } catch {
    throw new Error(`Invalid review page URL: "${url}" (check NEXT_PUBLIC_APP_URL)`);
  }
  return url;
}

function buildReviewPageComment(reviewPageUrl: string): string {
  return [
    "### 🎬 PrVod",
    "",
    "Your walkthrough is ready!",
    "",
    `▶️ <a href="${reviewPageUrl}" target="_blank" rel="noopener noreferrer">Open the review page</a>`,
    "",
    "---",
    "*Generated by [PrVod](https://prvod.dev)*",
  ].join("\n");
}

// buildErrorComment lives in a sibling module so it can be unit-tested without
// dealing with Next.js's restrictions on route-file exports.

const MAX_COMMENT_JSON_CHARS = 60_000;

function formatScriptBlock(scriptJson: unknown): string {
  const json = JSON.stringify(scriptJson, null, 2);
  const truncated = json.length > MAX_COMMENT_JSON_CHARS
    ? json.slice(0, MAX_COMMENT_JSON_CHARS) + "\n... (truncated)"
    : json;
  return "```json\n" + truncated + "\n```";
}

function buildScriptReadyComment(scriptJson: unknown | null): string {
  return [
    "### 🎬 PrVod",
    "",
    "Script generated! The PR analysis script is ready.",
    "",
    scriptJson ? formatScriptBlock(scriptJson) : "_No script output available_",
    "",
    "---",
    "*Generated by [PrVod](https://prvod.dev)*",
  ].join("\n");
}

function buildCancelledComment(): string {
  return [
    "### 🎬 PrVod",
    "",
    "Video generation was cancelled.",
    "",
    "---",
    "*Generated by [PrVod](https://prvod.dev)*",
  ].join("\n");
}

function isBotAuthoredIssueComment(comment: Record<string, unknown> | undefined): boolean {
  const user = (comment?.user as Record<string, unknown> | undefined) ?? undefined;
  const commenterLogin = (user?.login as string | undefined) ?? "";
  const commenterType = (user?.type as string | undefined) ?? "";
  const appSlug = (process.env.GITHUB_APP_SLUG ?? "").trim();
  const performedViaApp = comment?.performed_via_github_app as
    | Record<string, unknown>
    | undefined;
  const performedViaSlug = ((performedViaApp?.slug as string | undefined) ?? "").trim();

  // Debug context shared by every return path below. The bot guard silently
  // returning `false` on our own comment was the direct cause of a webhook
  // loop (https://prvod.dev internal) — logging the fields that feed into
  // the decision lets us diagnose any future miss without adding more round
  // trips. Sensitive data is not present on this payload.
  const guardContext = {
    commenterLogin,
    commenterType,
    appSlug: appSlug || "<unset>",
    performedViaSlug: performedViaSlug || "<none>",
  };

  if (commenterType.toLowerCase() === "bot") {
    logger.debug("Bot guard hit: commenter type is 'Bot'", guardContext);
    return true;
  }
  if (commenterLogin.endsWith("[bot]")) {
    logger.debug("Bot guard hit: commenter login ends with [bot]", guardContext);
    return true;
  }
  if (appSlug && commenterLogin === `${appSlug}[bot]`) {
    logger.debug("Bot guard hit: commenter login matches appSlug[bot]", guardContext);
    return true;
  }
  if (appSlug && performedViaSlug === appSlug) {
    logger.debug("Bot guard hit: performed_via_github_app.slug matches appSlug", guardContext);
    return true;
  }

  // Only log misses when the comment looks remotely bot-ish to avoid flooding
  // the logs with real user comments. A miss in any of these cases is worth
  // investigating because it's how we ended up in the loop originally.
  if (
    commenterType ||
    commenterLogin.includes("bot") ||
    commenterLogin.includes("[") ||
    performedViaSlug
  ) {
    logger.debug("Bot guard miss — comment processed as human", guardContext);
  }
  return false;
}

/**
 * Build a branded PR comment that tells users a video/script is being generated.
 * Posted immediately after job creation so PR participants know @prvod is working.
 *
 * Note: `popcornDuration` is intentionally not a parameter — per FR-003, both
 * standard and popcorn modes display "a video walkthrough".
 */
function buildAcknowledgementComment(scriptOnly: boolean, shortDuration: boolean): string {
  const outputType = scriptOnly
    ? "a script"
    : shortDuration
      ? "a short video walkthrough"
      : "a video walkthrough";

  return [
    "### 🎬 PrVod",
    "",
    `Generating ${outputType} of this PR - hang tight, it'll be ready in a few minutes.`,
    "",
    "---",
    "*Generated by [PrVod](https://prvod.dev)*",
  ].join("\n");
}

/** Build a branded PR comment notifying users the repo's daily video limit (50/day) has been reached. */
function buildRateLimitComment(): string {
  return [
    "### 🎬 PrVod",
    "",
    "This repository has reached its daily video limit. Please try again tomorrow.",
    "",
    "---",
    "*Generated by [PrVod](https://prvod.dev)*",
  ].join("\n");
}

function buildCommentForJob(job: VideoJob): { comment: string; commentType: string } {
  if (job.status === "completed") {
    if (job.videoUrl || job.objectKey) {
      try {
        return {
          comment: buildReviewPageComment(buildReviewPageUrl(job.id)),
          commentType: "success",
        };
      } catch (urlErr) {
        logger.error("Failed to build review page URL for completed job", {
          jobId: job.id,
          error: urlErr instanceof Error ? urlErr.message : String(urlErr),
        });
        return {
          comment: buildErrorComment("Review page URL could not be generated — please contact support"),
          commentType: "error",
        };
      }
    }
    if (job.scriptJson) {
      return { comment: buildScriptReadyComment(job.scriptJson), commentType: "script_ready" };
    }
    logger.error("Job marked as completed but missing video/script output — posting error comment", {
      jobId: job.id,
    });
    return {
      comment: buildErrorComment("Video generation succeeded but no output was found — please contact Jonathan"),
      commentType: "error",
    };
  }
  if (job.status === "cancelled") {
    return { comment: buildCancelledComment(), commentType: "cancelled" };
  }
  // Concatenate errorCode + errorMessage so `buildErrorComment` can branch
  // on the structured code (e.g. LLM_RATE_LIMITED_EXHAUSTED) without needing
  // fragile message-substring matching alone.
  const errorText = [job.errorCode, job.errorMessage].filter(Boolean).join(": ");
  return {
    comment: buildErrorComment(errorText || "Unknown error"),
    commentType: job.errorCode === "LLM_RATE_LIMITED_EXHAUSTED" ? "error_rate_limited" : "error",
  };
}

async function runWithRetry(
  runner: PipelineRunner,
  jobId: string,
  prContext: PRContext,
  jobRepo: IJobRepository,
  checkpointStore: IPipelineCheckpointStore | undefined,
  maxAttempts = 3,
  scriptOnly = false,
): Promise<VideoJob> {
  // Attempt 1: full run (or script-only run)
  logger.info("Pipeline attempt 1 starting", { jobId, scriptOnly });
  await runner.run(jobId, prContext, {
    scriptOnly,
  });

  let job = await jobRepo.findById(jobId);
  if (!job) throw new Error(`Job ${jobId} not found after run`);

  // Deterministic or already-exhausted failures will produce the same result
  // on a pipeline-level retry:
  //   - LLM_VALIDATION_EXHAUSTED: grounding/schema/coverage repair loops ran
  //     to their cap with the same inputs.
  //   - LLM_RATE_LIMITED_EXHAUSTED: the LLM-level retryLlmCall helper already
  //     did its exponential backoff and the provider is still refusing. A
  //     pipeline-level rerun would just burn through the same retry budget
  //     against the same upstream capacity problem.
  const NON_RETRYABLE_CODES = new Set([
    "LLM_VALIDATION_EXHAUSTED",
    "LLM_RATE_LIMITED_EXHAUSTED",
  ]);

  // Attempts 2–maxAttempts: retry from checkpoint (requires status to be "failed")
  for (let attempt = 2; attempt <= maxAttempts; attempt++) {
    if (job.status === "completed") break;
    if (job.status === "cancelled") {
      logger.info("Job cancelled before retry — stopping", { jobId, attempt });
      break;
    }
    if (job.status !== "failed") {
      logger.error("Job in unexpected state before retry — aborting retries", {
        jobId,
        status: job.status,
        attempt,
      });
      throw new Error(`Job ${jobId} stuck in unexpected state '${job.status}' before retry attempt ${attempt}`);
    }

    if (job.errorCode && NON_RETRYABLE_CODES.has(job.errorCode)) {
      logger.info("Job failed with non-retryable error — skipping remaining attempts", {
        jobId,
        errorCode: job.errorCode,
        attempt,
      });
      break;
    }

    let checkpoint = null;
    if (checkpointStore) {
      try {
        checkpoint = await checkpointStore.load(jobId);
      } catch (err) {
        logger.warn("Failed to load checkpoint before retry — falling back to full rerun", {
          jobId,
          attempt,
          error: err instanceof Error ? err.message : String(err),
        });
      }
    }
    if (checkpoint) {
      logger.info(`Pipeline attempt ${attempt} starting (checkpoint retry)`, { jobId });
      await runner.retry(jobId);
    } else {
      logger.info(`Pipeline attempt ${attempt} starting (full rerun)`, { jobId, scriptOnly });
      await runner.run(jobId, prContext, {
        scriptOnly,
      });
    }

    job = await jobRepo.findById(jobId);
    if (!job) throw new Error(`Job ${jobId} not found after retry attempt ${attempt}`);
  }

  logger.info("runWithRetry complete", { jobId, finalStatus: job.status });
  return job;
}

async function markJobFailedIfStillActive(
  jobRepo: IJobRepository,
  jobId: string,
  error: unknown,
): Promise<void> {
  const rawMessage = error instanceof Error ? error.message : String(error);
  const errorCode = error instanceof Error ? (error as { code?: unknown }).code : undefined;
  try {
    const currentJob = await jobRepo.findById(jobId);
    if (!currentJob || (currentJob.status !== "queued" && currentJob.status !== "processing")) {
      return;
    }
    const fields: Partial<VideoJob> = {
      errorCode: typeof errorCode === "string" ? errorCode : undefined,
      errorMessage: rawMessage,
    };
    await jobRepo.updateStatus(jobId, "failed", fields);
    logger.info("Marked active job failed after fire-and-forget pipeline rejection", {
      jobId,
      previousStatus: currentJob.status,
    });
  } catch (statusErr) {
    logger.error("Failed to mark active job as failed after pipeline rejection", {
      jobId,
      originalError: rawMessage,
      error: statusErr instanceof Error ? statusErr.message : String(statusErr),
    });
  }
}

async function safeUpdateDeliveryStatus(
  container: Awaited<ReturnType<typeof getContainer>>,
  deliveryId: string,
  status: "received" | "processed" | "skipped" | "failed",
  reason?: string,
): Promise<void> {
  const isTerminal = status === "processed" || status === "skipped" || status === "failed";
  try {
    await container.deliveryRepository.updateStatus(deliveryId, status, reason);
  } catch (err) {
    const logFn = isTerminal ? logger.error : logger.warn;
    logFn("Failed to update delivery status — delivery record may be permanently wedged", {
      deliveryId,
      status,
      reason,
      error: err instanceof Error ? err.message : String(err),
    });
  }
}

/**
 * Validate that parsed annotation fields + repo/PR identifiers are
 * sufficient to proceed. Returns either an early-exit response (validation
 * failed) or the narrowed `repoFullName` + `prNumber` values.
 */
async function validateAnnotatedFields(
  annotations: ReturnType<typeof parseAnnotations>,
  repoFullName: string | undefined,
  prNumber: number | undefined,
  deliveryId: string,
  container: Awaited<ReturnType<typeof getContainer>>,
  source: "PR description" | "PR comment",
): Promise<NextResponse | { repoFullName: string; prNumber: number }> {
  if (!annotations.hasAnnotation) {
    logger.warn(`No @prvod annotation found in ${source}`, { repoFullName, prNumber, deliveryId });
    await safeUpdateDeliveryStatus(container, deliveryId, "skipped", "no_annotation");
    return NextResponse.json({ status: "skipped", reason: "no_annotation" });
  }
  if (!repoFullName || !prNumber) {
    logger.error("Webhook payload missing required fields", { deliveryId, repoFullName, prNumber });
    await safeUpdateDeliveryStatus(container, deliveryId, "failed", "missing_required_fields");
    return NextResponse.json(
      { error: "BAD_REQUEST", message: "Missing repository or PR number" },
      { status: 400 },
    );
  }
  if (!REPO_FULL_NAME_REGEX.test(repoFullName)) {
    logger.error("Invalid repository full_name format", { deliveryId, repoFullName });
    await safeUpdateDeliveryStatus(container, deliveryId, "failed", "invalid_repository_name");
    return NextResponse.json(
      { error: "BAD_REQUEST", message: "Invalid repository name format" },
      { status: 400 },
    );
  }
  return { repoFullName, prNumber };
}

// ── POST handler ─────────────────────────────────────────────────────────────

export async function POST(request: Request) {
  // Rate limit by client IP before consuming the body.
  // Prefer x-real-ip (set by trusted reverse proxies like Nginx/Caddy to the
  // actual connecting client IP). Fall back to first x-forwarded-for entry.
  // Note: first xff entry is client-spoofable in append-mode proxies, but
  // using the last entry would bucket all requests under the proxy IP in
  // single-proxy deployments.
  const clientIp = request.headers.get("x-real-ip")
    ?? request.headers.get("x-forwarded-for")?.split(",")[0]?.trim()
    ?? "unknown";
  const { allowed, retryAfterMs } = webhookRateLimiter.check(clientIp);
  if (!allowed) {
    return NextResponse.json(
      { error: "RATE_LIMITED" },
      { status: 429, headers: { "Retry-After": String(Math.ceil(retryAfterMs / 1000)) } },
    );
  }

  // Read raw body first (stream is single-use; must happen before any other read)
  const rawBody = await request.text();

  const signature = request.headers.get("x-hub-signature-256");
  const eventType = request.headers.get("x-github-event");
  const deliveryId = request.headers.get("x-github-delivery") ?? "unknown";

  logger.info("Webhook received", { eventType, deliveryId });

  // Validate signature — fail fast if secret is unset or empty (misconfiguration)
  const secret = process.env.GITHUB_APP_WEBHOOK_SECRET;
  if (!secret) {
    logger.error("Webhook secret is not configured (set GITHUB_APP_WEBHOOK_SECRET)", { deliveryId });
    return NextResponse.json(
      { error: "UNAUTHORIZED" },
      { status: 401 },
    );
  }

  if (!verifyGitHubSignature(rawBody, signature, secret)) {
    logger.error("Webhook signature validation failed", { deliveryId });
    return NextResponse.json(
      { error: "UNAUTHORIZED", message: "Invalid or missing X-Hub-Signature-256" },
      { status: 401 },
    );
  }

  // Parse JSON (after raw body is captured)
  let payload: Record<string, unknown>;
  try {
    payload = JSON.parse(rawBody) as Record<string, unknown>;
  } catch {
    logger.error("Failed to parse webhook payload", { deliveryId });
    return NextResponse.json(
      { error: "BAD_REQUEST", message: "Invalid JSON body" },
      { status: 400 },
    );
  }

  // ── ping ──────────────────────────────────────────────────────────────────
  if (eventType === "ping") {
    logger.info("Ping event received", { deliveryId });
    return NextResponse.json({ status: "skipped", reason: "ping" });
  }

  // ── Hard-disable legacy (PAT) webhooks ────────────────────────────────────
  // GitHub App payloads always include installation.id; missing means PAT-based webhook
  const installationId = (payload.installation as { id?: number } | undefined)?.id;
  if (!installationId) {
    logger.warn("Legacy webhook rejected — missing installation.id. Configure a GitHub App webhook.", { deliveryId, eventType });
    return NextResponse.json(
      { error: "LEGACY_WEBHOOK_DISABLED", message: "Configure a GitHub App webhook" },
      { status: 410 },
    );
  }

  let container: Awaited<ReturnType<typeof getContainer>>;
  try {
    container = await getContainer();
  } catch (err) {
    logger.error("Failed to initialize container", {
      deliveryId,
      eventType,
      error: err instanceof Error ? err.message : String(err),
    });
    return NextResponse.json({ error: "INTERNAL_ERROR", message: "Service initialization failed" }, { status: 500 });
  }

  let redeliveryFailureReason: string | null = null;

  // ── Delivery deduplication ─────────────────────────────────────────────────
  // Atomic insert-based idempotency. Fail closed if the DB write fails.
  const repositoryId = (payload.repository as { id?: number } | undefined)?.id;
  let recorded: boolean;
  try {
    recorded = await container.deliveryRepository.record({
      deliveryId,
      eventType: eventType ?? "unknown",
      installationId,
      repositoryId,
    });
  } catch (err) {
    logger.error("Delivery deduplication write failed — rejecting for safety", {
      deliveryId,
      error: err instanceof Error ? err.message : String(err),
    });
    return NextResponse.json({ error: "SERVICE_UNAVAILABLE", message: "Deduplication check failed" }, { status: 503 });
  }
  if (!recorded) {
    let existingStatus = "unknown";
    try {
      const existing = await container.deliveryRepository.findByDeliveryId(deliveryId);
      existingStatus = existing?.status ?? "unknown";
      const isStaleReceived =
        existing?.status === "received" &&
        Date.now() - existing.receivedAt.getTime() >= RECEIVED_RETRY_AFTER_MS;
      if (existing?.status === "failed" || isStaleReceived) {
        redeliveryFailureReason = existing?.reason ?? null;
        const retryReason = existing?.status === "failed" ? "redelivery_retry_failed" : "redelivery_retry_stale_received";
        logger.info("Redelivery accepted for retryable delivery", {
          deliveryId,
          previousStatus: existing?.status,
          previousReason: existing?.reason ?? null,
        });
        await safeUpdateDeliveryStatus(container, deliveryId, "received", retryReason);
      } else {
        logger.info("Duplicate delivery skipped", { deliveryId, existingStatus });
        return NextResponse.json({ status: "skipped", reason: "duplicate_delivery" });
      }
    } catch (err) {
      logger.warn("Duplicate delivery lookup failed — skipping duplicate for safety", {
        deliveryId,
        existingStatus,
        error: err instanceof Error ? err.message : String(err),
      });
      return NextResponse.json({ status: "skipped", reason: "duplicate_delivery" });
    }
  }

  // ── installation events ────────────────────────────────────────────────────
  if (eventType === "installation") {
    const action = payload.action as string | undefined;
    const installationPayload = payload.installation as Record<string, unknown> | undefined;
    const account = installationPayload?.account as Record<string, unknown> | undefined;
    const accountLogin = (account?.login as string | undefined) ?? "";
    const accountType = (account?.type as string | undefined) ?? "User";

    logger.info("Installation event", { action, installationId, accountLogin });

    try {
      switch (action) {
        case "created":
        case "new_permissions_accepted": {
          const inst = await container.installationRepository.upsert({
            installationId,
            accountLogin,
            accountType,
          });
          const repos = (payload.repositories as Array<{ id: number; full_name: string }> | undefined) ?? [];
          for (const [idx, r] of repos.entries()) {
            try {
              await container.installationRepository.upsertRepository({
                installationRef: inst.id,
                githubRepositoryId: r.id,
                repoFullName: r.full_name,
              });
            } catch (repoErr) {
              logger.error("Failed to upsert repository in installation.created loop", {
                repoFullName: r.full_name,
                githubRepositoryId: r.id,
                index: idx,
                totalRepos: repos.length,
                deliveryId,
                error: repoErr instanceof Error ? repoErr.message : String(repoErr),
              });
              throw Object.assign(
                new Error(`Failed to upsert repository ${r.full_name} (id=${r.id}): ${repoErr instanceof Error ? repoErr.message : String(repoErr)}`),
                { cause: repoErr },
              );
            }
          }

          break;
        }
        case "deleted":
          // Evict before DB call so the cached token is always invalidated, even if markStatus fails
          if (container.githubAppTokenService) {
            container.githubAppTokenService.evict(installationId);
          } else {
            logger.warn("githubAppTokenService unavailable — token eviction skipped for deleted installation", { installationId, deliveryId });
          }
          await container.installationRepository.markStatus(installationId, "deleted");
          break;
        case "suspend":
          // Evict before DB call for the same reason
          if (container.githubAppTokenService) {
            container.githubAppTokenService.evict(installationId);
          } else {
            logger.warn("githubAppTokenService unavailable — token eviction skipped for suspended installation", { installationId, deliveryId });
          }
          await container.installationRepository.markStatus(installationId, "suspended");
          break;
        case "unsuspend":
          await container.installationRepository.markStatus(installationId, "active");
          break;
        default:
          logger.warn("Unhandled installation action", { action, deliveryId });
      }
    } catch (err) {
      logger.error("Failed to process installation event", {
        action,
        installationId,
        deliveryId,
        error: err instanceof Error ? err.message : String(err),
      });
      await safeUpdateDeliveryStatus(
        container,
        deliveryId,
        "failed",
        err instanceof Error ? err.message : String(err),
      );
      return NextResponse.json({ error: "INTERNAL_ERROR", message: "Failed to process installation event" }, { status: 500 });
    }
    await safeUpdateDeliveryStatus(container, deliveryId, "processed");
    return NextResponse.json({ status: "ok" });
  }

  // ── installation_repositories events ──────────────────────────────────────
  if (eventType === "installation_repositories") {
    const action = payload.action as string | undefined;
    try {
      const inst = await container.installationRepository.findByInstallationId(installationId);
      if (!inst) {
        logger.warn("installation_repositories event for unknown installation — repositories not updated", { installationId, deliveryId });
      } else {
        const added = (payload.repositories_added as Array<{ id: number; full_name: string }> | undefined) ?? [];
        for (const [idx, r] of added.entries()) {
          try {
            await container.installationRepository.upsertRepository({
              installationRef: inst.id,
              githubRepositoryId: r.id,
              repoFullName: r.full_name,
            });
          } catch (repoErr) {
            logger.error("Failed to upsert repository in installation_repositories loop", {
              repoFullName: r.full_name,
              githubRepositoryId: r.id,
              index: idx,
              totalAdded: added.length,
              deliveryId,
              error: repoErr instanceof Error ? repoErr.message : String(repoErr),
            });
            throw Object.assign(
              new Error(`Failed to upsert repository ${r.full_name} (id=${r.id}): ${repoErr instanceof Error ? repoErr.message : String(repoErr)}`),
              { cause: repoErr },
            );
          }
        }
        const removed = (payload.repositories_removed as Array<{ id: number }> | undefined) ?? [];
        for (const [idx, r] of removed.entries()) {
          try {
            await container.installationRepository.deactivateRepository(inst.id, r.id);
          } catch (repoErr) {
            logger.error("Failed to deactivate repository in installation_repositories loop", {
              githubRepositoryId: r.id,
              index: idx,
              totalRemoved: removed.length,
              deliveryId,
              error: repoErr instanceof Error ? repoErr.message : String(repoErr),
            });
            throw Object.assign(
              new Error(`Failed to deactivate repository id=${r.id}: ${repoErr instanceof Error ? repoErr.message : String(repoErr)}`),
              { cause: repoErr },
            );
          }
        }
      }
    } catch (err) {
      logger.error("Failed to process installation_repositories event", {
        action,
        installationId,
        deliveryId,
        error: err instanceof Error ? err.message : String(err),
      });
      await safeUpdateDeliveryStatus(
        container,
        deliveryId,
        "failed",
        err instanceof Error ? err.message : String(err),
      );
      return NextResponse.json({ error: "INTERNAL_ERROR", message: "Failed to update repository list" }, { status: 500 });
    }
    await safeUpdateDeliveryStatus(container, deliveryId, "processed");
    logger.info("installation_repositories event processed", { action, installationId, deliveryId });
    return NextResponse.json({ status: "ok" });
  }

  // ── Resolve installation record (required for PR events) ──────────────────
  let installation: InstallationRecord | null;
  try {
    installation = await container.installationRepository.findByInstallationId(installationId);
  } catch (err) {
    logger.error("Failed to resolve installation record", {
      installationId,
      deliveryId,
      error: err instanceof Error ? err.message : String(err),
    });
    await safeUpdateDeliveryStatus(
      container,
      deliveryId,
      "failed",
      err instanceof Error ? err.message : String(err),
    );
    return NextResponse.json({ error: "INTERNAL_ERROR", message: "Failed to resolve installation" }, { status: 500 });
  }
  if (!installation) {
    const installationPayload = payload.installation as Record<string, unknown> | undefined;
    const account = installationPayload?.account as Record<string, unknown> | undefined;
    const accountLogin = (account?.login as string | undefined) ?? "unknown";
    const accountType = (account?.type as string | undefined) ?? "User";
    try {
      installation = await container.installationRepository.upsert({
        installationId,
        accountLogin,
        accountType,
      });
      logger.info("Bootstrapped missing installation from webhook payload", {
        installationId,
        accountLogin,
        accountType,
      });
    } catch (err) {
      logger.error("Failed to bootstrap installation record", {
        installationId,
        deliveryId,
        error: err instanceof Error ? err.message : String(err),
      });
      await safeUpdateDeliveryStatus(
        container,
        deliveryId,
        "failed",
        err instanceof Error ? err.message : String(err),
      );
      return NextResponse.json({ error: "INTERNAL_ERROR", message: "Failed to resolve installation" }, { status: 500 });
    }
  }

  if (installation.status !== "active") {
    logger.warn("Webhook from inactive/unknown installation", { installationId, deliveryId, status: installation?.status });
    await safeUpdateDeliveryStatus(container, deliveryId, "skipped", "installation_inactive");
    return NextResponse.json({ status: "skipped", reason: "installation_inactive" });
  }
  const repoForMapping = payload.repository as { id?: number; full_name?: string } | undefined;
  if (repoForMapping?.id && repoForMapping.full_name) {
    // Best-effort: repository mapping is reconciled on every PR event; failure must not block the trigger.
    container.installationRepository.upsertRepository({
      installationRef: installation.id,
      githubRepositoryId: repoForMapping.id,
      repoFullName: repoForMapping.full_name,
    }).catch((err) => {
      logger.warn("Failed to upsert installation repository mapping (best-effort, not blocking)", {
        installationId,
        repositoryId: repoForMapping.id,
        repoFullName: repoForMapping.full_name,
        error: err instanceof Error ? err.message : String(err),
      });
    });
  }

  // ── pull_request (US1) ────────────────────────────────────────────────────
  if (eventType === "pull_request") {
    const action = payload.action as string | undefined;
    if (action !== "opened" && action !== "edited") {
      logger.warn("Unsupported pull_request action", { action, deliveryId });
      await safeUpdateDeliveryStatus(container, deliveryId, "skipped", "unsupported_action");
      return NextResponse.json({ status: "skipped", reason: "unsupported_action" });
    }

    const pr = payload.pull_request as Record<string, unknown> | undefined;
    const repo = payload.repository as Record<string, unknown> | undefined;
    const prBody = (pr?.body as string | null) ?? "";
    const repoFullName = repo?.full_name as string | undefined;
    const prNumber = pr?.number as number | undefined;

    // Bot-loop guard: skip if the PR was opened by our own bot
    const prAuthorLogin = ((pr?.user as Record<string, unknown> | undefined)?.login as string | undefined) ?? "";
    const appSlug = process.env.GITHUB_APP_SLUG ?? "";
    if (!appSlug) {
      logger.warn("GITHUB_APP_SLUG is not set — bot-loop guard is disabled for pull_request events");
    } else if (prAuthorLogin === `${appSlug}[bot]`) {
      logger.info("Skipping pull_request from bot to prevent loop", { prAuthorLogin, deliveryId });
      await safeUpdateDeliveryStatus(container, deliveryId, "skipped", "bot_comment");
      return NextResponse.json({ status: "skipped", reason: "bot_comment" });
    }

    logger.debug("Checking pull_request for @prvod annotation", { repoFullName, prNumber, action });

    const prAnnotations = parseAnnotations(prBody);
    const prValidation = await validateAnnotatedFields(prAnnotations, repoFullName, prNumber, deliveryId, container, "PR description");
    if (prValidation instanceof NextResponse) return prValidation;

    return handleAnnotatedTrigger(
      container,
      prValidation.repoFullName,
      prValidation.prNumber,
      deliveryId,
      prAnnotations.scriptOnly,
      installation,
      redeliveryFailureReason,
      prAnnotations.shortDuration,
      prAnnotations.popcornDuration,
      prAnnotations.deepdive,
    );
  }

  // ── issue_comment (US2) ───────────────────────────────────────────────────
  if (eventType === "issue_comment") {
    const action = payload.action as string | undefined;

    // Guard: only plain issue comments have no pull_request field on the issue object;
    // webhook should only fire on pull requests that are actually PRs
    if (action !== "created") {
      logger.warn("Unsupported issue_comment action", { action, deliveryId });
      await safeUpdateDeliveryStatus(container, deliveryId, "skipped", "unsupported_action");
      return NextResponse.json({ status: "skipped", reason: "unsupported_action" });
    }

    const issue = payload.issue as Record<string, unknown> | undefined;
    const comment = payload.comment as Record<string, unknown> | undefined;
    const repo = payload.repository as Record<string, unknown> | undefined;

    // issue.pull_request is present when the "issue" is actually a PR
    if (!issue?.pull_request) {
      logger.warn("issue_comment is on a plain issue, not a PR", { deliveryId });
      await safeUpdateDeliveryStatus(container, deliveryId, "skipped", "not_pr_comment");
      return NextResponse.json({ status: "skipped", reason: "not_pr_comment" });
    }

    const commentBody = (comment?.body as string) ?? "";
    const repoFullName = repo?.full_name as string | undefined;
    const prNumber = issue?.number as number | undefined;

    // Bot-loop guard: skip app-authored/bot-authored comments. Do not rely on
    // an exact slug match because development/staging apps may use a different
    // login (for example `prvod-dev[bot]`) than production.
    const commenterLogin = ((comment?.user as Record<string, unknown> | undefined)?.login as string | undefined) ?? "";
    const commenterType = ((comment?.user as Record<string, unknown> | undefined)?.type as string | undefined) ?? "";
    if (isBotAuthoredIssueComment(comment)) {
      logger.info("Skipping issue_comment from bot to prevent loop", {
        commenterLogin,
        commenterType,
        deliveryId,
      });
      await safeUpdateDeliveryStatus(container, deliveryId, "skipped", "bot_comment");
      return NextResponse.json({ status: "skipped", reason: "bot_comment" });
    }

    logger.debug("Checking issue_comment for @prvod annotation", { repoFullName, prNumber });

    const commentAnnotations = parseAnnotations(commentBody);
    const commentValidation = await validateAnnotatedFields(commentAnnotations, repoFullName, prNumber, deliveryId, container, "PR comment");
    if (commentValidation instanceof NextResponse) return commentValidation;

    return handleAnnotatedTrigger(
      container,
      commentValidation.repoFullName,
      commentValidation.prNumber,
      deliveryId,
      commentAnnotations.scriptOnly,
      installation,
      redeliveryFailureReason,
      commentAnnotations.shortDuration,
      commentAnnotations.popcornDuration,
      commentAnnotations.deepdive,
    );
  }

  // ── unsupported event type ─────────────────────────────────────────────────
  logger.warn("Unsupported event type", { eventType, deliveryId });
  await safeUpdateDeliveryStatus(container, deliveryId, "skipped", "unsupported_action");
  return NextResponse.json({ status: "skipped", reason: "unsupported_action" });
}

// ── Shared handler for both US1 and US2 ──────────────────────────────────────

async function handleAnnotatedTrigger(
  container: Awaited<ReturnType<typeof getContainer>>,
  repoFullName: string,
  prNumber: number,
  deliveryId: string,
  scriptOnly = false,
  installation: InstallationRecord,
  redeliveryFailureReason: string | null = null,
  shortDuration = false,
  popcornDuration = false,
  deepdive = false,
): Promise<NextResponse> {
  logger.info("@prvod annotation detected", { repoFullName, prNumber, deliveryId, scriptOnly, shortDuration, popcornDuration, deepdive, installationId: installation.installationId });

  // Once-per-PR enforcement: only applies to full-video jobs.
  // Script-only requests are lightweight and allowed to run multiple times per PR.
  let existingJob: VideoJob | null = null;
  if (!scriptOnly) {
    try {
      existingJob = await container.jobRepository.findAnyByPR(repoFullName, prNumber, installation.id);
    } catch (err) {
      logger.error("Failed to query existing job", {
        deliveryId,
        repoFullName,
        prNumber,
        error: err instanceof Error ? err.message : String(err),
      });
      await safeUpdateDeliveryStatus(
        container,
        deliveryId,
        "failed",
        err instanceof Error ? err.message : String(err),
      );
      return NextResponse.json({ error: "INTERNAL_ERROR", message: "Database error" }, { status: 500 });
    }

    // Script-only completions (scriptJson set, no videoUrl) don't block full video jobs
    const isScriptOnlyCompletion =
      existingJob?.status === "completed" && existingJob.scriptJson && !existingJob.videoUrl;

    if (existingJob && !isScriptOnlyCompletion) {
      // Case 1: Redelivery specifically for a missed comment — replay it.
      if (redeliveryFailureReason?.startsWith("comment_post_failed:")) {
        const { comment, commentType } = buildCommentForJob(existingJob);
        try {
          await container.githubService.postComment(repoFullName, prNumber, comment, installation.installationId);
          logger.info("Recovered missed PR comment on redelivery", {
            repoFullName,
            prNumber,
            jobId: existingJob.id,
            commentType,
            deliveryId,
          });
          await safeUpdateDeliveryStatus(container, deliveryId, "processed", "comment_replayed");
          return NextResponse.json({
            status: "ok",
            reason: "comment_replayed",
            jobId: existingJob.id,
          });
        } catch (err) {
          await safeUpdateDeliveryStatus(
            container,
            deliveryId,
            "failed",
            `comment_post_failed: ${err instanceof Error ? err.message : String(err)}`,
          );
          return NextResponse.json(
            { error: "INTERNAL_ERROR", message: "Failed to replay PR comment" },
            { status: 500 },
          );
        }
      }

      // Case 2: Existing job is stuck in queued/processing (crash recovery).
      // Only recover on redeliveries — a fresh webhook while the job is actively
      // processing should return job_exists, not start a parallel pipeline run.
      const isStuck = existingJob.status === "queued" || existingJob.status === "processing";
      if (isStuck && redeliveryFailureReason !== null) {
        logger.warn("Existing job is stuck, resuming pipeline on redelivery", {
          repoFullName,
          prNumber,
          jobId: existingJob.id,
          jobStatus: existingJob.status,
          deliveryId,
          redeliveryFailureReason,
        });
        // Fall through to pipeline execution below — reuse the existing job ID
        // by skipping the "job_exists" early return.
      } else {
        // Case 3: Failed jobs should not block retries — allow a fresh attempt.
        if (existingJob.status === "failed") {
          logger.info("Allowing retry — previous job failed", {
            repoFullName,
            prNumber,
            existingJobId: existingJob.id,
            deliveryId,
          });
          existingJob = null;
        }

        // Case 4: Job already reached a terminal state — allow a new video.
        // If the user explicitly requests @prvod again, they want a fresh run.
        if (existingJob && ["completed", "cancelled"].includes(existingJob.status)) {
          logger.info("Allowing new job — existing job already terminal", {
            repoFullName,
            prNumber,
            existingJobId: existingJob.id,
            existingJobStatus: existingJob.status,
            deliveryId,
          });
          existingJob = null;
        } else if (existingJob) {
          logger.warn("Job already exists for PR, skipping", {
            repoFullName,
            prNumber,
            jobId: existingJob.id,
            jobStatus: existingJob.status,
          });
          await safeUpdateDeliveryStatus(container, deliveryId, "skipped", "job_exists");
          return NextResponse.json({
            status: "skipped",
            reason: "job_exists",
            jobId: existingJob.id,
          });
        }
      }
    }
  }

  // Daily rate limit check (FR-007): 50 videos/day/repo.
  // Skip when: (a) script-only requests don't count toward the video quota,
  // (b) recovering a stuck job (no new video is being created).
  const isRecoveringStuckJob = existingJob !== null
    && (existingJob.status === "queued" || existingJob.status === "processing")
    && redeliveryFailureReason !== null;
  if (!scriptOnly && !isRecoveringStuckJob) {
    let recentCount: number;
    try {
      const oneDayAgo = new Date(Date.now() - 24 * 60 * 60 * 1000);
      recentCount = await container.jobRepository.countRecentByRepo(
        repoFullName, oneDayAgo, installation.id, /* excludeScriptOnly */ true,
      );
    } catch (err) {
      logger.error("Failed to check daily rate limit", {
        deliveryId, repoFullName, prNumber,
        error: err instanceof Error ? err.message : String(err),
      });
      await safeUpdateDeliveryStatus(
        container, deliveryId, "failed",
        err instanceof Error ? err.message : String(err),
      );
      return NextResponse.json({ error: "INTERNAL_ERROR", message: "Database error" }, { status: 500 });
    }
    if (recentCount >= 50) {
      logger.warn("Daily video limit reached", { repoFullName, count: recentCount, deliveryId });
      try {
        await container.githubService.postComment(repoFullName, prNumber, buildRateLimitComment(), installation.installationId);
      } catch (commentErr) {
        logger.error("Failed to post rate-limit comment — user will not see feedback on PR", {
          repoFullName, prNumber, deliveryId, installationId: installation.installationId,
          error: commentErr instanceof Error ? commentErr.message : String(commentErr),
        });
      }
      await safeUpdateDeliveryStatus(container, deliveryId, "skipped", "rate_limit_exceeded");
      return NextResponse.json({ status: "skipped", reason: "rate_limit_exceeded" }, { status: 429 });
    }
  }

  // Fetch full PR context from GitHub
  let prContext: PRContext;
  try {
    prContext = await container.githubService.fetchPRContext(repoFullName, prNumber, installation.installationId);
    if (popcornDuration) {
      prContext.durationMode = "popcorn";
    } else if (shortDuration) {
      prContext.durationMode = "short";
    }
    prContext.deepdive = deepdive;
    logger.debug("Fetched PR context from GitHub", {
      repoFullName,
      prNumber,
      durationMode: prContext.durationMode,
      deepdive: prContext.deepdive,
      title: prContext.prTitle,
      description: prContext.prDescription,
      issueNumbers: prContext.issues.map((issue) => issue.number).join(","),
    });
  } catch (err) {
    logger.error("Failed to fetch PR context from GitHub", {
      deliveryId,
      repoFullName,
      prNumber,
      error: err instanceof Error ? err.message : String(err),
    });
    await safeUpdateDeliveryStatus(
      container,
      deliveryId,
      "failed",
      err instanceof Error ? err.message : String(err),
    );
    return NextResponse.json({ error: "INTERNAL_ERROR", message: "Failed to fetch PR data" }, { status: 500 });
  }

  // Reuse existing stuck job, or create a new one.
  // When a stuck job is being recovered (fall-through from above), skip creation.
  const stuckJob = existingJob && (existingJob.status === "queued" || existingJob.status === "processing")
    ? existingJob
    : null;
  let job: VideoJob;

  if (stuckJob) {
    job = stuckJob;
    logger.info("Reusing stuck job for pipeline recovery", { jobId: job.id, repoFullName, prNumber });
  } else {
    try {
      job = await container.jobRepository.create({
        repoFullName,
        prNumber,
        installationRef: installation.id,
        githubInstallationId: installation.installationId,
        triggeredVia: "github_app_webhook",
        deliveryId,
        scriptOnly,
        repoIsPrivate: prContext.isPrivate,
        ...((popcornDuration || shortDuration || deepdive)
          ? {
              metricsJson: {
                ...(popcornDuration ? { durationMode: "popcorn" as const } : {}),
                ...(!popcornDuration && shortDuration ? { durationMode: "short" as const } : {}),
                ...(deepdive ? { deepdive: true } : {}),
              },
            }
          : {}),
      });
    } catch (err) {
      if ((err as { code?: string }).code === "23505") {
        try {
          const racedJob = await container.jobRepository.findActiveByPR(
            repoFullName,
            prNumber,
            installation.id,
          );
          if (racedJob) {
            logger.warn("Active job won create race, skipping duplicate pipeline start", {
              jobId: racedJob.id,
              repoFullName,
              prNumber,
              deliveryId,
            });
            await safeUpdateDeliveryStatus(container, deliveryId, "skipped", "job_exists_race");
            return NextResponse.json({
              status: "skipped",
              reason: "job_exists",
              jobId: racedJob.id,
            });
          }
          // 23505 but no active job found — ambiguous state; return 500 for webhook retry
          logger.error("23505 constraint violation but no active job found — ambiguous race state, returning 500 for retry", {
            deliveryId, repoFullName, prNumber,
          });
          await safeUpdateDeliveryStatus(container, deliveryId, "failed", "race_ambiguous");
          return NextResponse.json({ error: "Race condition unresolved" }, { status: 500 });
        } catch (lookupErr) {
          logger.error("Failed to look up racing job after 23505 constraint violation — race recovery incomplete", {
            deliveryId, repoFullName, prNumber,
            error: lookupErr instanceof Error ? lookupErr.message : String(lookupErr),
          });
          await safeUpdateDeliveryStatus(container, deliveryId, "failed", "race_lookup_failed");
          return NextResponse.json({ error: "Race recovery failed" }, { status: 500 });
        }
      }
      logger.error("Failed to create job", {
        deliveryId,
        repoFullName,
        prNumber,
        error: err instanceof Error ? err.message : String(err),
      });
      await safeUpdateDeliveryStatus(
        container,
        deliveryId,
        "failed",
        err instanceof Error ? err.message : String(err),
      );
      return NextResponse.json({ error: "INTERNAL_ERROR", message: "Failed to create job" }, { status: 500 });
    }
    if (job.deliveryId !== deliveryId) {
      logger.warn("Create returned an existing active job from another delivery, skipping duplicate pipeline start", {
        jobId: job.id,
        repoFullName,
        prNumber,
        existingDeliveryId: job.deliveryId,
        deliveryId,
      });
      await safeUpdateDeliveryStatus(container, deliveryId, "skipped", "job_exists_race");
      return NextResponse.json({
        status: "skipped",
        reason: "job_exists",
        jobId: job.id,
      });
    }

    // If create() returned an existing active job (repository 23505 fallback),
    // verify durationMode matches — otherwise we'd run the wrong pipeline on it.
    const returnedDurationMode =
      (job.metricsJson as { durationMode?: string } | null)?.durationMode ?? "default";
    const returnedDeepdive =
      (job.metricsJson as { deepdive?: boolean } | null)?.deepdive === true;
    const requestedDurationMode = popcornDuration ? "popcorn" : shortDuration ? "short" : "default";
    if (returnedDurationMode !== requestedDurationMode || returnedDeepdive !== deepdive) {
      logger.warn("Create returned active job with different durationMode/deepdive, skipping", {
        jobId: job.id,
        returnedDurationMode,
        requestedDurationMode,
        returnedDeepdive,
        requestedDeepdive: deepdive,
        repoFullName,
        prNumber,
        deliveryId,
      });
      await safeUpdateDeliveryStatus(container, deliveryId, "skipped", "duration_mode_conflict");
      return NextResponse.json({
        status: "skipped",
        reason: "duration_mode_conflict",
        jobId: job.id,
      });
    }
    logger.info("Job created", { jobId: job.id, repoFullName, prNumber, shortDuration });
  }

  // ── Acknowledgement comment (FR-001, FR-006) ─────────────────────────────
  // Post a branded "Generating..." comment on the PR so participants know the
  // pipeline is running. This happens synchronously before the fire-and-forget
  // pipeline dispatch, guaranteeing the comment is visible by the time the
  // HTTP 202 response returns.
  //
  // Two separate try-catches because posting to GitHub and persisting the flag
  // are independent failure modes with different consequences:
  //   - postComment fails → no comment on PR, but pipeline proceeds (FR-006)
  //   - updateStatus fails → comment is on PR but flag stays false in DB,
  //     so a redelivery may post a duplicate (logged at ERROR for visibility)
  if (!job.statusCommentPosted) {
    logger.debug("Posting acknowledgement comment", {
      jobId: job.id, repoFullName, prNumber,
      mode: scriptOnly ? "script" : shortDuration ? "short" : popcornDuration ? "popcorn" : "standard",
    });
    let ackPosted = false;
    try {
      const ackComment = buildAcknowledgementComment(scriptOnly, shortDuration);
      await container.githubService.postComment(repoFullName, prNumber, ackComment, installation.installationId);
      ackPosted = true;
    } catch (postErr) {
      logger.warn("Failed to post acknowledgement comment — proceeding with pipeline", {
        jobId: job.id, repoFullName, prNumber,
        error: postErr instanceof Error ? postErr.message : String(postErr),
      });
    }
    if (ackPosted) {
      try {
        await container.jobRepository.updateStatus(job.id, job.status, { statusCommentPosted: true } as Partial<VideoJob>);
        job.statusCommentPosted = true;
      } catch (dbErr) {
        logger.error("Acknowledgement posted but failed to persist flag — duplicate possible on redelivery", {
          jobId: job.id, repoFullName, prNumber,
          error: dbErr instanceof Error ? dbErr.message : String(dbErr),
        });
        job.statusCommentPosted = true; // prevent duplicate within this request
      }
      logger.info("Acknowledgement comment posted", { jobId: job.id, repoFullName, prNumber });
    }
  }

  // Respond immediately (async pipeline runs fire-and-forget)
  const runner = createPipelineRunner(container, {
    githubService: true,
    diffSource: true,
  });

  // Fire-and-forget: run pipeline then post comment
  runWithRetry(runner, job.id, prContext, container.jobRepository, container.checkpointStore, 3, scriptOnly)
    .then(async (finalJob) => {
      const { comment, commentType } = buildCommentForJob(finalJob);

      try {
        await container.githubService.postComment(repoFullName, prNumber, comment, installation.installationId);
        logger.info("PR comment posted", { jobId: finalJob.id, repoFullName, prNumber, commentType });
        void safeUpdateDeliveryStatus(container, deliveryId, "processed");
      } catch (commentErr) {
        logger.error("Failed to post PR comment — video may exist but PR author was not notified", {
          jobId: finalJob.id,
          repoFullName,
          prNumber,
          commentType,
          videoUrl: finalJob.videoUrl ?? null,
          error: commentErr instanceof Error ? commentErr.message : String(commentErr),
        });
        void safeUpdateDeliveryStatus(
          container,
          deliveryId,
          "failed",
          `comment_post_failed: ${commentErr instanceof Error ? commentErr.message : String(commentErr)}`,
        );
      }
    })
    .catch(async (err) => {
      const rawMessage = err instanceof Error ? err.message : String(err);
      const errorCode = err instanceof Error ? (err as { code?: unknown }).code : undefined;
      logger.error("Pipeline fire-and-forget error", {
        jobId: job.id,
        repoFullName,
        prNumber,
        error: rawMessage,
      });
      await markJobFailedIfStillActive(container.jobRepository, job.id, err);
      try {
        // Include the error code (if present on the thrown Error) so the
        // comment builder can surface an LLM-rate-limit-specific message.
        const enrichedMessage = typeof errorCode === "string"
          ? `${errorCode}: ${rawMessage}`
          : rawMessage;
        const errorComment = buildErrorComment(enrichedMessage);
        await container.githubService.postComment(repoFullName, prNumber, errorComment, installation.installationId);
      } catch (commentErr) {
        logger.error("Failed to post error comment after pipeline failure", {
          jobId: job.id,
          error: commentErr instanceof Error ? commentErr.message : String(commentErr),
        });
      }
      void safeUpdateDeliveryStatus(
        container,
        deliveryId,
        "failed",
        rawMessage,
      );
    });

  return NextResponse.json({ status: "queued", jobId: job.id });
}
